'use strict';

const Hapi = require('hapi');
const fetch = require('node-fetch');

const images = [
  // Comments start with "//", blank lines ignored.

  // OMG:
  "https://lh3.googleusercontent.com/-OUw4Q9scVeA/T88ag2ms7nI/AAAAAAAAGYk/k61JJgULnL0/s320/90.gif",
  // "https://lh4.googleusercontent.com/-CRSjITDmb4I/USZTvuI_07I/AAAAAAAAIlU/CLKU1HbMC3c/w497-h373/dsf43.gif",
  // "https://lh4.googleusercontent.com/-pH8_D-vVIgg/UlAvwHk7_vI/AAAAAAAEvBc/TMdu9MdclPE/w426-h244/b0cb01d6jw1e6i4o62dnpg206y03z7wj.gif",

  // Your favorite animated GIFs. What’s your favorite animated GIF? We asked Webmakers #— and got back a TON. Two veritable goldmines of what’s come in so far: here and here. #What’s your favorite? Add it here.
  "https://i.imgur.com/3fPDPhl.gif",
  "https://i.imgur.com/YETyuWJ.gif",
  "https://i.imgur.com/jXXnG9a.gif",
  "https://i.imgur.com/7Bo2HBb.gif",
  "https://i.imgur.com/VPFVw.gif",
  "https://media.tumblr.com/tumblr_ma7rqzY6zQ1qis5xyo1_400.gif",
  "https://i.imgur.com/6xaYo.gif",
  "https://i.imgur.com/N0Qe0.gif",
  "https://i.imgur.com/2hyBM.gif",
  "https://i.imgur.com/yjfDD.gif",
  "https://media.tumblr.com/tumblr_lwlcls5ra01qzrlhgo1_r1_500.gif",
  "https://media.tumblr.com/tumblr_lmuonu2zHq1qzs6oc.gif",
  "https://i1.kym-cdn.com/photos/images/original/000/343/462/79a.gif",
  "https://i.imgur.com/f7mgB.gif",
  "https://curv.net/lulz/32r23.gif",
  "https://i.imgur.com/KTWfi.gif",
  "https://i.imgur.com/hLkIc.gif",
  "https://www.pbh2.com/wordpress/wp-content/uploads/2012/03/when-the-person-you-like-asks-you-who-you-like.gif",
  "https://media.tumblr.com/tumblr_mbcmdl61wk1rx8lgjo1_500.gif",
  "https://i.imgur.com/0p5Tk.gif",
  "https://i.imgur.com/tTRVY.gif",
  "https://i.imgur.com/HqxTX.gif",
  "https://i.imgur.com/g77ft.gif",
  "https://i.imgur.com/fAHW6.gif",
  "https://i.imgur.com/ztBrV.gif",
  "https://i.imgur.com/fSV89.gif",
  "https://bukk.it/hidecat.gif",
  "https://bukk.it/sadhouse.gif",
  "https://i.imgur.com/vxKOi.gif",
  "https://i.imgur.com/gJs10.gif",
  "https://i.imgur.com/MkoST.gif",
  "https://i.imgur.com/MtQzT.gif",
  "https://i.imgur.com/e7Sf4.gif",
  "https://i.imgur.com/vQfL2mf.gif",
  "https://bukk.it/thebird.gif",
  "https://i.imgur.com/QF2Wv.gif",
  "https://i.imgur.com/Mb0O4.gif",
  "https://media.tumblr.com/tumblr_lvi4wbq9rM1qch9gxo1_250.gif",
  "https://i.imgur.com/0T39c.gif",
  "https://i.imgur.com/eSKDJJG.gif",
  "https://media.tumblr.com/tumblr_lw3ucb4OBY1qbohddo1_400.gif",
  "https://i.imgur.com/haxBHL8.gif",
  "https://i.imgur.com/x3QvhQB.gif",
  "https://i.imgur.com/3Vsyc.gif",
  "https://media.tumblr.com/bd49ff2209c2572abb7598cb688a5384/tumblr_mgahzpccz91riz8uqo1_500.gif",
  // "https://www.omgif.net/wp-content/uploads/2011/09/Darth-Vader-goes-to-disneyland.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-03.gif",
  "https://i.imgur.com/nVyTCM6.gif",
  // "https://lh4.googleusercontent.com/-CRSjITDmb4I/USZTvuI_07I/AAAAAAAAIlU/CLKU1HbMC3c/w497-h373/dsf43.gif",
  "https://media.tumblr.com/e61e41535c2d97548bd354257ca245c9/tumblr_mijvzzypCi1s5lmqko1_400.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-17.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-25.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-09.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-07.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-34.gif",
  // "https://img.gawkerassets.com/post/7/2013/02/owl4.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-13.gif",
  "https://i.imgur.com/5fmDKDm.gif",
  "https://i.imgur.com/QP2Ptq3.gif",
  "https://i.imgur.com/7scNWUI.gif",
  "https://i.imgur.com/GlFJlgc.gif",
  "https://i.imgur.com/8LpZJzd.gif",
  "https://i.imgur.com/gI1yCkT.gif",
  "https://i.imgur.com/NN3ea7D.gif",
  "https://i.imgur.com/7j5GvSZ.gif",
  "https://i.imgur.com/ZJPE0qh.gif",
  "https://i.imgur.com/DYM7B.gif",
  "https://i.imgur.com/HivY0bh.gif",
  "https://i.imgur.com/wm9Srgj.gif",
  "https://i.imgur.com/q638n.gif",
  "https://i.imgur.com/5nrEk.gif",
  "https://i.imgur.com/bWOEx.gif",
  "https://i.imgur.com/csNn5.gif",
  "https://media.tumblr.com/fa34873f5ea1f358a831d71716457e0f/tumblr_miimsrLGYI1s410g9o1_500.gif",
  "https://media.tumblr.com/e3268d0912c7fa27162cb4ec0b6ac7a4/tumblr_mi6pquwAce1s410g9o1_500.gif",
  "https://media.tumblr.com/bc56a117f0999390d89ea8fa5cd2624c/tumblr_mi7eu4GIMt1s410g9o2_r1_400.gif",
  "https://www.gif.tv/gifs/giftv-1995-programming.gif",
  "https://www.gif.tv/gifs/giftv-2908-catcartoon.gif",
  "https://www.gif.tv/gifs/giftv-697-ludicrousspeed.gif",
  "https://www.gif.tv/gifs/giftv-1156-chew.gif",
  "https://www.gif.tv/gifs/giftv-964-ralph.gif",
  "https://www.gif.tv/gifs/giftv-1190-retroroad.gif",
  "https://www.gif.tv/gifs/giftv-89-grindbarrel.gif",
  "https://www.gif.tv/gifs/giftv-2186-flippush.gif",
  "https://i.imgur.com/TkMiY.gif",
  // "http://www.gifbin.com/bin/022012/1329760487_slinky_on_a_treadmill.gif",
  "https://i.imgur.com/0SBuk.gif",
  "https://i.imgur.com/DYO6X.gif",
  "https://i.imgur.com/i3ZWA.gif",
  "https://i.imgur.com/joCZx.gif",
  "https://i.imgur.com/1n8zR.gif",
  "https://i.imgur.com/8ZYNp.gif",
  "https://lh5.googleusercontent.com/--dfPifelbUI/UR1uLzBUFWI/AAAAAAAAGvg/ZRfDkATgDhw/s400/154.gif",
  "https://lh5.googleusercontent.com/-pc42P8qYBmY/UR1uKM9L5eI/AAAAAAAAGu8/YyVHWtu3lxA/s500/150.gif",
  "https://lh5.googleusercontent.com/-ZGhtww8mdeg/UR1uJmNFSAI/AAAAAAAAGu0/N6j6TztraQc/s214/147.gif",
  "https://lh3.googleusercontent.com/-lM-1EFJEXMo/UR1uJR2YNYI/AAAAAAAAGuo/COqapHo_4KA/s250/148.gif",
  "https://lh4.googleusercontent.com/-zZLr2PDNWjc/UR1uI2MP1II/AAAAAAAAGuc/VOty2r0SeK4/s499/146.gif",
  "https://lh6.googleusercontent.com/-mpQhfskeUEM/UR1uH8t1IuI/AAAAAAAAGuM/9Um8X1JK3ec/s245/143.gif",
  "https://lh4.googleusercontent.com/-x5vqi1Nru5E/UNH4iqpwIKI/AAAAAAAAGo4/LVWQlnRKx6s/s499/138.gif",
  "https://lh3.googleusercontent.com/-NpTaGH776Y4/UNH4i-AipdI/AAAAAAAAGoo/EgWUDH08VGQ/s499/140.gif",
  "https://lh6.googleusercontent.com/-YvIKR8Pin04/UNH4kZFzc4I/AAAAAAAAGpE/GHP1hXMb_D4/s290/142.gif",
  "https://lh4.googleusercontent.com/-C8uQV6jvxh8/UNH4ipTksKI/AAAAAAAAGo0/YB-d_J_-li4/s235/139.gif",
  "https://lh3.googleusercontent.com/-LRMOoQYIynY/UNH4iMul_gI/AAAAAAAAGoY/eJHrtOsd2QI/s275/137.gif",
  "https://lh4.googleusercontent.com/-uvn2pajNjwE/UNH4g4zfrKI/AAAAAAAAGn0/hegLc8TV4-k/s499/132.gif",
  "https://lh3.googleusercontent.com/-pc0CGADfQi8/UNH4gxxOSkI/AAAAAAAAGn4/F_RetiYnzLE/s245/133.gif",
  "https://lh5.googleusercontent.com/-Zk_xoSha4jA/UNH4gWKmdsI/AAAAAAAAGns/1Acx-WAEVMA/s400/131.gif",
  "https://lh3.googleusercontent.com/-9MxHOLLtSwE/UNH4f23mI8I/AAAAAAAAGno/yEHouQRN9qQ/s320/129.gif",
  "https://lh3.googleusercontent.com/--w8YwSzqJ2o/UIpRE9gx9TI/AAAAAAAAGmQ/oDV7_gy1fgo/s497/125.gif",
  "https://lh6.googleusercontent.com/-cfet9ZGVdEs/UIpQ8jdpHyI/AAAAAAAAGls/c7Bkg7n3Hts/s500/124.gif",
  "https://lh4.googleusercontent.com/-WDENMs9-9Go/UIpQ8VtoPnI/AAAAAAAAGlw/DlGT87t_eKU/s350/123.gif",
  "https://lh4.googleusercontent.com/-z1YWcRd2eok/UIpQ7SEk1MI/AAAAAAAAGlk/LZW81-tzS4k/s308/121.gif",
  "https://lh5.googleusercontent.com/-88-_CsLuB2E/UIpQ4wvPxwI/AAAAAAAAGlE/HdOdW5PtW-U/s480/118.gif",
  "https://lh3.googleusercontent.com/-W_Hk1TtHea4/UIpQ4ltyB7I/AAAAAAAAGlA/Om9Ij6i5nOc/s450/117.gif",
  "https://lh4.googleusercontent.com/-kJYg1sF71sU/UIpQ2kuPk3I/AAAAAAAAGks/Zrl6q0hbPIg/s480/115.gif",
  "https://lh5.googleusercontent.com/-NBVCT9QuTS0/UIpQ2D8iIWI/AAAAAAAAGkk/Ns5l5KK9dxM/s400/113.gif",
  "https://lh6.googleusercontent.com/-zXvkqJgtAXQ/UIpQ1CEPiwI/AAAAAAAAGkQ/Fh-cTKPcJWQ/s500/110.gif",
  "https://lh3.googleusercontent.com/-21huKAxNM0E/UC-wMKQPtKI/AAAAAAAAGeQ/08ULez8tWDs/s320/109.gif",
  "https://lh6.googleusercontent.com/-frg-6Q9_g0Y/UC-wKfvV-EI/AAAAAAAAGd4/xM-68kLSqnA/s248/105.gif",
  "https://lh6.googleusercontent.com/-qTH541uX9sA/UC-wL2sbJmI/AAAAAAAAGeU/EF8_c5pXTNA/s500/108.gif",
  "https://media.topito.com/wp-content/uploads/2013/01/code-18.gif",
  "https://i.imgur.com/xoOmhJC.gif",
  "https://i.imgur.com/RwG0QIj.gif",
  "https://bukk.it/huaghfluahgjk.gif",
  "https://i.imgur.com/ISf3l04.gif",
  "https://petitrocks.files.wordpress.com/2013/02/bruce-almighty-typing-animated.gif",
  "https://i.imgur.com/6MWRE.gif",
  // "https://themockdock.com/wp-content/uploads/2012/10/funny-gif-horse-mask-storm.gif",
  "https://i.imgur.com/k4l8FOa.gif",
  "https://i.imgur.com/ysQ71eM.gif",
  "https://lh3.googleusercontent.com/-gTAAbtWcug4/URB8q1VTjWI/AAAAAAAAAJw/xHfGmxjw4fc/s510/HorseMaskFan.gif",
  "https://i.imgur.com/YtPTVoz.gif",
  "https://i.imgur.com/nE9ZD.gif",
  "https://i.imgur.com/dnMjc.gif",
  "https://i.imgur.com/6oz7VBF.gif",
  // "http://blog.johnath.com/images/bestday.jpg",
  "https://farm9.staticflickr.com/8045/8402972393_4b8d08bbff_b.jpg",
  "https://media.tumblr.com/a5ea2af6c67db8d5e773e9668789613f/tumblr_mhn69m7F1S1r7w8cbo1_250.gif",
  "https://i.imgur.com/DzqIVGg.gif",
  "https://i.imgur.com/8J1QP.gif",
  "https://i.imgur.com/4IKuaxu.gif",
  // "https://stream1.gifsoup.com/view/394818/dramatic-cat-o.gif",
  "https://i.imgur.com/Cz3GDeS.jpg",
  "https://i.imgur.com/4nsI9Gv.gif",
  "https://i.imgur.com/AG4WhKZ.gif",
  "https://i.imgur.com/DXPlH0E.gif",
  // "https://assets0.ordienetworks.com/misc/OBAMA_SixGuns.gif",
  "https://i.imgur.com/wLPd0.gif",
  "https://i.imgur.com/spMvd.gif",
  "https://i.imgur.com/ZMMVU.gif",
  "https://i.imgur.com/joz3pKU.gif",
  // "https://stream1.gifsoup.com/view6/2355311/nyan-cat-o.gif",
  "https://i.imgur.com/NUSAa.gif",
  "https://i.imgur.com/KgcxN.gif",
  "https://media.tumblr.com/tumblr_mbc4n2UHwS1r115hxo1_500.gif",
  "https://forgifs.com/gallery/d/207969-1/Homer-hunts-spiders.gif",
  "https://i.imgur.com/kLjVtOG.gif",
  "https://i.imgur.com/U432X63.gif",
  "https://media.tumblr.com/tumblr_m3bllp7p3L1qi6wuyo1_500.gif",
  "https://i.imgur.com/t5VHGck.gif",
  "https://i.imgur.com/fVERhd6.gif",
  "https://i.imgur.com/fwO14LU.gif",
  "https://i.imgur.com/s4ENe0v.gif",
  "https://i.imgur.com/kz3dS3N.gif",
  "https://i.imgur.com/O73QJDH.gif",
  "https://i.imgur.com/NWq5WIq.gif",
  "https://i.imgur.com/zHz1x6O.gif",

  "https://i.imgur.com/Iaj6X.gif",
  // "https://stream1.gifsoup.com/view3/1172142/running-into-a-wall-o.gif",
  "https://bukk.it/googly.gif",
  "https://thedailyquirk.files.wordpress.com/2013/03/tumblr_mh55hioyyi1qeqpbco5_250.gif?w=584",
  "https://i.imgur.com/nPdpKE3.gif",
  "https://i.imgur.com/nZNWt.gif",
  "https://i.imgur.com/WJypQw9.gif",
  "https://media.tumblr.com/542a066e4d3dc2c962baba62d86f748c/tumblr_mk6s3dzjLf1qbdynmo1_400.gif",
  "https://i.imgur.com/zoWXk.gif",
  "https://i.imgur.com/2ZHoaA0.gif",
  "https://i.imgur.com/Q3cUg29.gif",
  "https://i.imgur.com/VFKyWBz.gif",
  "https://i.imgur.com/3T2NeUd.gif",
  "https://i.imgur.com/DzzsNsA.jpg",
  "https://i.imgur.com/Ri855cK.gif",
  "https://i.imgur.com/0RSkLtl.gif",
  "https://i.imgur.com/jQjWaYr.gif",
  "https://i.imgur.com/Lc3CpMz.gif",
  // "https://www.omgif.net/wp-content/uploads/2012/02/close-enough.gif",
  "https://i.imgur.com/Npx9yb6.gif",
  "https://i.imgur.com/CBP3qdO.gif",
  // "https://dl.dropboxusercontent.com/u/7054348/hypnocat.gif",
  // "https://img.gawkerassets.com/img/18jwg2yqfyjg4gif/ku-medium.gif",
  "https://i.imgur.com/k0ESvLQ.jpg",
  // "https://people-mozilla.org/~smartell/meme/milton-stapler.gif",
  "https://i.imgur.com/O9vu4XV.gif",
  "https://i.imgur.com/StFpJCY.gif",
  "https://i.imgur.com/nRGuj.gif",
  "https://i.imgur.com/tOqhKh4.gif",
  "https://i.imgur.com/JyoCCab.gif",
  // "https://fordfortoronto.mattelliott.ca/misc/ford-ani/ford-bonk.gif",
  "https://i.imgur.com/nATPNJb.gif",
  "https://i.imgur.com/b1XpFy1.gif",
  // "https://www.omgif.net/wp-content/uploads/2013/03/police-troll.gif",
  "https://i.imgur.com/TJbeWKb.gif",
  "https://i.imgur.com/wQ3BXnh.gif",
  "https://i.imgur.com/ZwLtozI.gif",
  "https://i.imgur.com/8aSUopb.gif?1",
  "https://i.imgur.com/3gbPRx3.gif",
  "https://media.tumblr.com/tumblr_ma7rrfiHJj1ruav3u.gif",
  "https://media.tumblr.com/tumblr_lxfq0it8CN1qmp5o7.gif",
  "https://i.imgur.com/GQI2bWz.gif",
  "https://i.imgur.com/ls7adO5.gif",
  "https://media.tumblr.com/tumblr_mdwqhpDPdq1rlseiyo1_500.gif",
  "https://media.tumblr.com/d068204f08a33c31a325206ae934e511/tumblr_inline_mltv6gv4HH1qz4rgp.gif",
  "https://media.tumblr.com/1fca2227f76ec56b563b075ecdcd21e6/tumblr_mltydrysHn1qdlh1io1_400.gif",
  "https://media.tumblr.com/tumblr_m5gncrUWzk1qe6oczo1_500.gif",
  "https://3.bp.blogspot.com/-7z0k3_qJU28/Td71pvbc9dI/AAAAAAAANxE/_vGeB2kMMYk/s1600/mythbusted.gif",
  "https://i.imgur.com/AEZYis2.gif",
  "https://i.imgur.com/43sf9NL.gif",
  "https://media.tumblr.com/e3df0e3c38874ff6c76d3a9a691fa4cb/tumblr_inline_mi4lhudtNe1qz4rgp.gif",
  "https://i.imgur.com/prvOkD3.gif",
  "https://i.imgur.com/fDS9rPs.gif",
  "https://i.imgur.com/XoiX3AH.gif",
  "https://media.tumblr.com/4200a39ac228d431dab85f6ebb307b77/tumblr_misqnjrC361s4nfigo1_500.gif",
  "https://media.tumblr.com/tumblr_m7y8ngxwcO1qg39ewo1_500.gif",
  "https://i.imgur.com/i4x5g.gif",
  "https://i.imgur.com/UqxQh54.gif",
  "https://i.imgur.com/JZq6LXx.gif",
  "https://i.imgur.com/Y6nQ6Da.gif",
  "https://i.imgur.com/H5V4aU4.jpg",
  "https://i.imgur.com/Ext7QfH.gif",
  "https://media.tumblr.com/tumblr_m5ws79TQqT1r4231fo1_500.gif",
  "https://i.imgur.com/cbYsVKe.gif",
  "https://i.imgur.com/PiAERJ4.gif",
  "https://i.imgur.com/eVnnbXL.gif",
  "https://i.imgur.com/ZE1S6zH.gif",
  "https://cdn.iwastesomuchtime.com/3282012115703ohnoyoudiunt.gif",
  "https://4.bp.blogspot.com/-MPQMRhc9kIo/T5AomwwtPkI/AAAAAAAAGr0/oKNp96e1I14/s1600/Loch+Ness+monster+giraffe.gif",
  "https://i.imgur.com/NKkdDOm.gif",
  "https://i.imgur.com/EvdrNsW.gif",
  "https://i.imgur.com/96ufw.gif",
  "https://i.imgur.com/8BKxVJ2.gif",
  "https://i.imgur.com/ACVeOf6.jpg",
  "https://i.imgur.com/uJ8DtGJ.jpg",
  "https://i.imgur.com/zWxu2.gif",
  "https://media.tumblr.com/tumblr_lvew3rlcue1r675ano1_500.gif",
  "https://i.imgur.com/Djpe8py.gif",
  "https://i.chzbgr.com/maxW500/7400391680/hE9DAB195/",
  "https://i.imgur.com/xUm0P.gif",
  "https://media.tumblr.com/tumblr_m4t4yb28Ml1r25dmi.gif",
  "https://i.imgur.com/6RYy1.gif",
  "https://blog.ninapaley.com/wp-content/uploads/2013/05/tiles_hex_progressive3shortBW.gif",
  "https://media.tumblr.com/6986166623219890aecb766874bcdd14/tumblr_mldjvvNI0Z1r6uouqo1_500.gif",
  "https://i.imgur.com/kTNYLX3.gif",
  "https://media.giphy.com/media/H0oRkYAjvlfws/200.gif",
  "https://media.giphy.com/media/fD2tbCl4snSi4/200.gif",
  "https://i.imgur.com/lqYb9.gif",
  "https://i.imgur.com/gIo133a.gif",
  "https://i.imgur.com/44rhz6z.gif",
  "https://i.imgur.com/XsPqVes.gif",
  "https://i.imgur.com/vQMzUw2.gif",
  "https://i.imgur.com/h0s0F.gif",
  "https://belieber.files.wordpress.com/2011/09/animals-cute-tired-corgi.gif",
  "https://media.tumblr.com/tumblr_lpy0arzcxi1qbidbp.gif",
  "https://media.tumblr.com/tumblr_lnl0shCsbD1qbytf4o1_250.gif",
  "https://i.imgur.com/qFd3s9O.gif",
  "https://i.imgur.com/45GoAIj.gif",
  "https://i.imgur.com/VCIFcyP.gif",
  "https://i.chzbgr.com/maxW500/7435535104/h51AD6723/",
  "https://i.imgur.com/t50UyBG.gif",
  // "https://fordfortoronto.mattelliott.ca/misc/gta-growth.gif",
  "https://i.imgur.com/gigXXAr.gif",
  "https://i.imgur.com/7pe2k.gif",
  "https://i.imgur.com/d7vi2.gif",
  "https://i.imgur.com/axipm8w.gif",
  "https://i.chzbgr.com/maxW500/7460359168/h58F55FEF/",
  "https://i.imgur.com/E5GMVy1.gif",
  "https://i.imgur.com/o2v2nIX.gif",
  "https://media.tumblr.com/tumblr_ll5f0fwi9t1qdcwfto1_500.gif",
  "https://i.imgur.com/1eHXndF.gif",
  "https://media.tumblr.com/5b8557ed697342ccc5af437d798121c6/tumblr_mmm9mbNe381rw9dz1o1_500.gif",
  "https://i.imgur.com/D3NcD6e.gif",
  "https://hugelolcdn.com/i/4362.gif",
  "https://cdn1.sbnation.com/imported_assets/1107680/234015_o.gif",
  "https://media.tumblr.com/aec9cbbdf826f98307e6d5f3d544a4c2/tumblr_mmlrbhGDAO1qaqutao1_500.gif",
  "https://i.imgur.com/GvIPBPl.gif",
  "https://i.imgur.com/G0ociY7.gif",
  "https://i.imgur.com/4KNky.gif",
  "https://i.imgur.com/XxU6Byf.gif",
  // "https://lh5.googleusercontent.com/--IpD_0aq4vg/TmN3kooppkI/AAAAAAAAKsk/tYNPyN2MqSA/w401-h301-no/Internetism2_Micael_Reynaud.gif",
  "https://i.imgur.com/dixVSzG.gif",
  "https://i.imgur.com/KmDrXzI.gif",
  "https://i.imgur.com/wzOYc69.gif",
  "https://i.imgur.com/VT2EIUh.gif",
  "https://i.imgur.com/7FM8f4Z.jpg",
  "https://i.imgur.com/SEYzcaI.gif",
  "https://i.imgur.com/HIpMZiM.gif",
  "https://i.imgur.com/u6dFLEW.gif",
  "https://i.imgur.com/AjWWM7k.gif",
  "https://i.imgur.com/G7NOi4G.gif",
  "https://i.imgur.com/33Ff9.gif",
  "https://media.boingboing.net/wp-content/uploads/2013/01/1356472619182.gif",
  "https://i.imgur.com/0mlMrVc.gif",
  "https://i.imgur.com/4AiXLeW.gif",
  "https://i.imgur.com/3Q0pqUB.gif",
  "https://i.imgur.com/zkS3fpi.gif",
  "https://i.imgur.com/cM6LT8O.gif",
  "https://i.imgur.com/YE9pTvf.gif",
  "https://i.imgur.com/w7L7Rdk.gif",
  "https://i.imgur.com/kFsLySu.gif",
  "https://i.imgur.com/EboeSn6.gif",
  "https://i.imgur.com/O4aOuHJ.gif",
  "https://i.imgur.com/fEwgaaQ.gif",
  "https://i.imgur.com/3MdmPfi.gif",
  "https://media2.giphy.com/media/3Q8Ugu0pGFoCQ/giphy.gif",
  "https://i.imgur.com/7yMLHxq.jpg",
  "https://www.leblogdukitsch.com/wp-content/uploads/2013/05/cari_vander_yacht_03.gif",
  "https://www.leblogdukitsch.com/wp-content/uploads/2013/05/cari_vander_yacht_05.gif",
  "https://www.leblogdukitsch.com/wp-content/uploads/2013/05/cari_vander_yacht_08.gif",
  "https://www.leblogdukitsch.com/wp-content/uploads/2013/05/cari_vander_yacht_09.gif",
  "https://www.leblogdukitsch.com/wp-content/uploads/2013/05/cari_vander_yacht_12.gif",
  "https://i.imgur.com/yqmp5KB.gif",
  "https://i.imgur.com/Dz3nk.gif",
  "https://media.tumblr.com/tumblr_m2yvtzc1xP1rnlzlh.gif",
  "https://www.pxleyes.com/images/users/S/Sarah06/4422/fullsize/506353703f9b5.gif",
  // From Sense Appeal!!!  :) +1
  "https://i.imgur.com/hPgDVWn.gif",
  "https://i.imgur.com/csRo1ky.gif",
  "https://i.imgur.com/VQLGJOL.gif",
  "https://i.imgur.com/Gp0VpHS.gif",
  "https://i.imgur.com/bPBynFM.gif",
  "https://static.tumblr.com/49927eca8ed9c61eab4471de25617787/dlgx4mm/r1dmm595c/tumblr_static_tumblr_mbd530nmxl1qmary5o1_500.gif",
  "https://i.imgur.com/Fr3oexg.gif",
  "https://i.imgur.com/zAevpsx.gif",
  "https://i.imgur.com/zxHLr2e.gif",
  "https://i.imgur.com/MqJ4Syu.gif",
  "https://i.imgur.com/298fdEi.gif",
  "https://i.imgur.com/Y9OvB8G.gif",
  "https://media1.giphy.com/media/Wj15lkl3N3Lig/giphy.gif",
  "https://i.imgur.com/0N2Em3C.gif",
  "https://ic.pics.livejournal.com/tragemata/25155229/2931623/2931623_original.gif",
  "https://i.imgur.com/hYt0E.gif",
  "https://i.imgur.com/DuBec8q.gif",
  "https://i.imgur.com/xwktzoy.gif",
  "https://i.imgur.com/Aw6smQZ.gif",
  "https://i.imgur.com/bdbpw0G.gif",
  "https://i.imgur.com/tTBWPrv.gif",
  "https://media.tumblr.com/8445bbadf50d8016bc8b48dd5390750e/tumblr_mol446WZG61s14nvmo1_400.gif",
  // "https://img.gawkerassets.com/img/18pp7ks88gh7lgif/k-xlarge.gif",
  "https://memeorama.com/wp-content/uploads/2012/09/aww-yiss-owl.gif",
  "https://i.imgur.com/kp8te.gif",
  "https://alexsexton.com/images/js_app_deploy/gruntbuild.gif",
  // "https://img.gawkerassets.com/img/18qfl6nkyd2hcgif/original.gif",
  "https://i.imgur.com/v943HnM.jpg",
  "https://i.imgur.com/kMkYQ7U.gif",
  "https://i.imgur.com/drU7Dze.gif",
  "https://digg.com/static/images/reader/importing-animated-logo.gif",
  "https://bwinton.latte.ca/camera/weblog/FaceGif.gif",
  // "https://f.cl.ly/items/1u122i1H0p2g2G0c3D2F/your-giffed-face.gif",
  "https://jlongster.com/s/your-giffed-face.gif",
  "https://i.imgur.com/GCR63I3.gif",
  "https://paul.cx/public/conference.gif",
  "https://paul.cx/public/dramatic.gif",
  "https://img-fotki.yandex.ru/get/9310/78716754.9a/0_d6736_2e7ee005_orig",
  "https://cdn.iwastesomuchtime.com/7102012230133strobecat.gif",
  "https://media.tumblr.com/1e94c2a75e129bc97a0e4893040de316/tumblr_mod2r2FnzX1qhd8sao1_500.gif",
  "https://media.tumblr.com/tumblr_md8xr1NLGi1r3q7iqo1_500.jpg",
  "https://ic.pics.livejournal.com/tragemata/25155229/3133004/3133004_original.gif",
  "https://i.imgur.com/9QaQjD2.gif",
  "https://i.imgur.com/Shhggfj.gif",
  "https://i.imgur.com/MNCOSnp.gif",
  "https://media1.giphy.com/media/10HAKAqaHdHf8Y/giphy.gif",
  "https://ic.pics.livejournal.com/tragemata/25155229/3170339/3170339_original.gif",
  "https://ic.pics.livejournal.com/tragemata/25155229/3279569/3279569_original.gif",
  "https://media.tumblr.com/e14a67c79d2d480155356b6fe53c19f1/tumblr_mpc2rhQW6k1qcrv20o1_r3_500.gif",
  "https://aperiodical.com/wp-content/uploads/2013/01/tumblr_mboslkYgPR1qc0s10o1_500.gif",
  "https://i.imgur.com/f21JG84.gif",
  "https://media.tumblr.com/283ba4114f6472639aec79d5fe7e6d52/tumblr_mfznecyUqi1r3ovdbo1_400.gif",
  "https://i.imgur.com/DFMmwGi.png",
  "https://i.imgur.com/cJiIH8d.gif",

  // Nopetopus!
  "https://media.tumblr.com/tumblr_m641p2JoAH1qbl202.gif",
  "https://i.imgur.com/8vCpFuH.gif",
  "https://i.imgur.com/4BtLipY.gif",
  "https://i.imgur.com/yGDTKoQ.gif",
  "https://i.imgur.com/W38JC8D.gif",
  "https://i.imgur.com/J4dvVCP.gif",
  "https://i.imgur.com/O4XS55f.gif",
  // "https://lh3.googleusercontent.com/-4tOsH4JGc_g/UeMzjOtgsmI/AAAAAAAAQwI/cLo3ZsUAcYg/w959-h649-no/H0nEf.gif",
  "https://img-fotki.yandex.ru/get/9362/78716754.9c/0_d79f2_6e3c3de3_orig",
  "https://img-fotki.yandex.ru/get/9106/78716754.9d/0_d7a5f_346f0621_orig",
  "https://img-fotki.yandex.ru/get/9066/78716754.9e/0_d7bf1_355a8d7a_orig",
  "https://img-fotki.yandex.ru/get/6719/78716754.9d/0_d7a4d_3e3e4b11_orig",
  "https://media.tumblr.com/ed068d90d55d672c023ef4d0edb85b63/tumblr_mq16d61cUr1qzpsuoo1_400.gif",
  // "https://assets0.ordienetworks.com/images/GifGuide/DealWithIt/bettywhitedealwithit.gif",
  // "https://bugzilla.mozilla.org/extensions/BMO/web/images/mozchomp.gif",
  "https://i.imgur.com/qPsmesl.gif",
  "https://media.tumblr.com/2939641e015e9ddc0a66109223a259dc/tumblr_mq9fc9psRs1ry46hlo1_400.gif",
  "https://i.imgur.com/JncYyD9.gif",
  "https://bukk.it/howidowebdesign.gif",
  "https://1.bp.blogspot.com/-wWiKKrt6BOo/UYHYbSC2K3I/AAAAAAAAEIc/8OO_t39jwGI/s320/Nathan-Fillion-Loss-For-Words-Reaction-Gif.gif",
  "https://bwinton.latte.ca/camera/weblog/UniChelsea.gif",
  "https://i.imgur.com/uIi89.gif",
  "https://i.imgur.com/uPM8dvj.gif",
  // "https://img.gawkerassets.com/img/18uoifri4lu85gif/original.gif",
  "https://i.imgur.com/PWCjMiP.gif",
  "https://i.imgur.com/SEwFeGh.gif",
  "https://i.imgur.com/HR4cjLS.jpg",
  "https://media.tumblr.com/6427b004d662e8815f3646298050322e/tumblr_mpw4slV1Xm1r84rgno1_400.gif",
  "https://themetapicture.com/media/funny-gif-kitty-surf-escape.gif",
  "https://worleygig.files.wordpress.com/2013/05/baby-sloth.jpg",
  "https://i.imgur.com/f7Uj7Sw.gif",
  "https://media.tumblr.com/1571e8696caef1d1568f562b9427174b/tumblr_mqpnu3NaVr1r2geqjo1_500.gif",
  "https://i.imgur.com/hcsrl7Z.gif",
  "https://media.tumblr.com/82715e2d6552ca5b3b2d20cefcdc99cd/tumblr_inline_mqilb78pyf1qz4rgp.gif",
  "https://media.tumblr.com/39c307ef642f9ae99bfacd8387a02742/tumblr_mfgs4hGeyX1rmdsrwo1_250.gif",
  "https://dribbble.s3.amazonaws.com/users/14268/screenshots/1151139/boom.gif",
  "https://i.imgur.com/0sA3dQd.gif",
  "https://i.imgur.com/0rpD6q7.gif",
  "https://i.imgur.com/dAtcCfH.gif",
  "https://i.imgur.com/Kh2Osoy.gif",
  "https://i.imgur.com/l5HfJo0.gif",
  "https://i.imgur.com/mVdrJw7.gif",
  "https://i.imgur.com/o3aqu59.gif",
  "https://i.imgur.com/LBkdf.gif",
  // "https://www.gifbin.com/bin/072010/1280482491_dealwithit-the-long-version.gif",
  "https://i.imgur.com/Ha2wD19.gif",
  "https://i.imgur.com/hy6vDb1.gif",
  "https://i.imgur.com/CuzTPTR.gif",
  "https://i.imgur.com/awEIRSE.gif",
  "https://i.imgur.com/QDXAN1U.gif",
  "https://i.imgur.com/LlpGldr.gif",
  "https://i.imgur.com/0eC7n05.gif",
  "https://i.imgur.com/ItzXHYd.gif",
  "https://i.imgur.com/iPJoKj6.gif",
  "https://i.imgur.com/kzRu0V5.gif",
  "https://i.imgur.com/MhIPx7R.gif",
  "https://i.imgur.com/UdH39ZX.gif",
  "https://i.imgur.com/rgfCtol.gif",
  "https://i.imgur.com/beZsUve.gif",
  "https://i.imgur.com/4ibsGlI.gif",
  "https://i.imgur.com/93ryWxf.gif",
  "https://i.imgur.com/fuhl2ks.gif",
  "https://i.imgur.com/59VBDWt.gif",
  "https://i.imgur.com/bjygxts.gif",
  "https://i.imgur.com/4zeycVT.gif",
  "https://i.imgur.com/9vwaC6l.gif",
  "https://i.imgur.com/a26308n.gif",
  "https://i.imgur.com/uiaAeb7.gif",
  "https://i.imgur.com/rTtr4fE.gif",
  "https://i.imgur.com/S1TWW4v.gif",
  "https://i.imgur.com/sS69ox2.gif",
  "https://i.imgur.com/z9Du5yo.gif",
  "https://i.imgur.com/LKA2W0v.gif",
  "https://i.imgur.com/QABP3iX.gif",
  "https://i.imgur.com/RDK9R7C.gif",
  "https://i.imgur.com/VexpqEL.gif",
  "https://i.imgur.com/nf00QGF.gif",
  "https://i.imgur.com/7KlLlVs.gif",
  "https://i.imgur.com/9g0CbDn.gif",
  "https://i.imgur.com/ueYvu8i.gif",
  "https://i.imgur.com/wGwxQhQ.gif",
  "https://i.imgur.com/CRs3cQN.gif",
  "https://i.imgur.com/YXTfzMW.gif",
  "https://i.imgur.com/faW1Git.gif",
  "https://i.imgur.com/9j2HlOM.gif",
  "https://i.imgur.com/qn9O3tD.gif",
  "https://i.imgur.com/6R5OJI2.gif",
  "https://i.imgur.com/txqUGXW.gif",
  "https://i.imgur.com/L1nX1Pd.gif",
  "https://i.imgur.com/vrhQzyA.gif",
  "https://i.imgur.com/iebUGwo.gif",
  "https://i.imgur.com/vWJylrB.gif",
  "https://i.imgur.com/0l26fCJ.gif",
  "https://i.imgur.com/zbH9pof.gif",
  "https://i.imgur.com/4OkDfZ4.gif",
  "https://i.imgur.com/fso6HEM.gif",
  "https://i.imgur.com/Ss4FCzF.gif",
  "https://i.imgur.com/YYPRFH4.gif",
  "https://i.imgur.com/wsDd07f.gif",
  "https://i.imgur.com/PU3UcIY.gif",
  "https://i.imgur.com/UkT7jcm.gif",
  "https://i.imgur.com/yl1pXAv.gif",
  "https://i.imgur.com/9HT3mrT.gif",
  "https://i.imgur.com/kfR4kF8.gif",
  "https://i.imgur.com/TehylgF.gif",
  "https://i.imgur.com/FHRtmeZ.gif",
  "https://i.imgur.com/Ms95Eev.gif",
  "https://i.imgur.com/Ooag3C6.gif",
  "https://i.imgur.com/xmSFbqt.gif",
  "https://i.imgur.com/FHEZ5Lc.gif",
  "https://i.imgur.com/JXbWegd.gif",
  "https://i.imgur.com/MzWsFVh.gif",
  "https://i.imgur.com/eQavZHX.gif",
  "https://i.imgur.com/h1JSsJo.gif",
  "https://i.imgur.com/tkqR9JY.gif",
  "https://i.imgur.com/IMdd2Od.gif",
  "https://i.imgur.com/iGkKiOu.gif",
  "https://i.imgur.com/jxROvqX.gif",
  "https://i.imgur.com/9uGXXpb.gif",
  "https://i.imgur.com/S8k08sU.gif",
  "https://i.imgur.com/twKRrdl.gif",
  "https://i.imgur.com/F6NGkuu.gif",
  "https://i.imgur.com/iOdNIAE.gif",
  "https://i.imgur.com/ByvwUGX.gif",
  "https://i.imgur.com/jGCcLqn.gif",
  "https://i.imgur.com/YjbptWs.gif",
  "https://i.imgur.com/N8yyvRM.gif",
  "https://i.imgur.com/g9a4IrV.gif",
  "https://i.imgur.com/9orGm0d.gif",
  "https://i.imgur.com/FnHmmrU.gif",
  "https://i.imgur.com/qczFsse.gif",
  "https://i.imgur.com/6AJvxmv.gif",
  "https://i.imgur.com/2SMDFjg.gif",
  "https://i.imgur.com/HQEdhaf.gif",
  "https://i.imgur.com/sDp5bix.gif",
  "https://i.imgur.com/RM3ntM3.gif",
  "https://i.imgur.com/lpglGBi.gif",
  "https://i.imgur.com/45O1t6p.gif",
  "https://i.imgur.com/6YZF7ht.gif",
  "https://i.imgur.com/QAxjmRW.gif",
  "https://i.imgur.com/p0sBDNM.gif",
  "https://i.imgur.com/QF9LgCO.gif",
  "https://i.imgur.com/OjcHC4k.gif",
  "https://i.imgur.com/jqdIcni.gif",
  "https://i.imgur.com/ITwZ00O.gif",
  "https://i.imgur.com/AVfgGQO.gif",
  "https://i.imgur.com/dd1vyhK.gif",
  "https://i.imgur.com/Mgmkc2o.gif",
  "https://i.imgur.com/pdWJtJr.gif",
  "https://i.imgur.com/6zYA4gj.gif",
  "https://i.imgur.com/jdSgLjA.gif",
  "https://i.imgur.com/uVojr1S.gif",
  "https://i.imgur.com/ixXhPIs.gif",
  "https://i.imgur.com/vvQaraR.gif",
  "https://i.imgur.com/fqgZjkx.gif",
  "https://i.imgur.com/Xh865vt.gif",
  "https://i.imgur.com/BWtkIZs.gif",
  "https://i.imgur.com/I8vFxkR.gif",
  "https://i.imgur.com/ziDUQ1X.gif",
  "https://i.imgur.com/J85cywv.gif",
  "https://i.imgur.com/gXGyuCK.gif",
  "https://i.imgur.com/W6otUVO.gif",
  "https://i.imgur.com/cRq4lLd.gif",
  "https://i.imgur.com/EIK9fwX.gif",
  "https://i.imgur.com/1sg5kOq.gif",
  "https://i.imgur.com/BnHA4rw.gif",
  "https://i.imgur.com/Dullg39.gif",
  "https://i.imgur.com/qOPQIqz.gif",
  "https://i.imgur.com/gdWWZO0.gif",
  "https://i.imgur.com/jKWg4Bt.gif",
  "https://i.imgur.com/iaEd1zN.gif",
  "https://i.imgur.com/7srwrmg.gif",
  "https://i.imgur.com/TrRLf2T.gif",
  "https://i.imgur.com/MGn55Cc.gif",
  "https://i.imgur.com/0sbasbp.gif",
  "https://i.imgur.com/CdkVixv.gif",
  "https://i.imgur.com/bs435lo.gif",
  "https://i.imgur.com/JY29qng.gif",
  "https://i.imgur.com/HCK8ocO.gif",
  "https://i.imgur.com/ULVNw50.gif",
  "https://i.imgur.com/J0Tg9XI.gif",
  "https://i.imgur.com/G0TonrZ.gif",
  "https://i.imgur.com/JNXq7wj.gif",
  "https://i.imgur.com/2ULU3HK.gif",
  "https://i.imgur.com/tLcgsos.gif",
  "https://i.imgur.com/KZxbalq.gif",
  "https://i.imgur.com/n4MCLVh.gif",
  "https://i.imgur.com/bi4g60F.gif",
  "https://i.imgur.com/YZChmYt.gif",
  "https://i.imgur.com/wMwNHv2.gif",
  "https://i.imgur.com/7dGVh9I.gif",
  "https://i.imgur.com/EbS8CKf.gif",
  "https://i.imgur.com/ApTSNgC.gif",
  "https://i.imgur.com/jQjtBPm.gif",
  "https://i.imgur.com/ehMT7mS.gif",
  "https://i.imgur.com/jy9zmfw.gif",
  "https://i.imgur.com/06wOB06.gif",
  "https://i.imgur.com/6tIxZ7O.gif",
  "https://i.imgur.com/XhTLnuF.gif",
  "https://i.imgur.com/uH8mbuc.gif",
  "https://i.imgur.com/ZXvJN9H.gif",
  "https://i.imgur.com/O5AOj2U.gif",
  "https://i.imgur.com/BFuJ4Bm.gif",
  "https://i.imgur.com/zftjfVv.gif",
  "https://i.imgur.com/eoVG3Gp.gif",
  "https://i.imgur.com/74spz2L.gif",
  "https://i.imgur.com/9lp8uD5.gif",
  "https://i.imgur.com/ag1OGax.gif",
  "https://i.imgur.com/RcE6Lot.gif",
  "https://i.imgur.com/pvoj4sV.gif",
  "https://i.imgur.com/Pd6OhNm.gif",
  "https://i.imgur.com/gAFtZeJ.gif",
  "https://i.imgur.com/IM8BaEd.gif",
  "https://i.imgur.com/KhK4v9V.gif",
  "https://media.tumblr.com/50d9e427883996f598ba75ec41269f8e/tumblr_mpuumzgBbk1ry46hlo1_400.gif",
  "https://twistedsifter.files.wordpress.com/2013/08/internet-usage-of-the-world-based-on-time-of-day_2.gif",
  "https://media.tumblr.com/737666faa2d722da289d00bae18778f5/tumblr_mp3l26jj9K1ryq07lo1_500.gif",
  "https://i.imgur.com/qXSaYIy.gif",
  "https://uberhumor.com/wp-content/uploads/2013/08/staMNLO.gif",
  "https://i.imgur.com/mMaWbSH.gif",
  "https://i.imgur.com/MkUEAeX.gif",
  "https://media.tumblr.com/tumblr_ljfk65tKLi1qgeyd8o1_500.gif",
  "https://blog.ninapaley.com/wp-content/uploads/2013/08/Ziz_photo_movie.gif",
  // "https://s2.favim.com/orig/28/blue-donuts-hell-homer-simpsons-Favim.com-231447.gif",
  "https://media.tumblr.com/dffa51e3c30f4057eb273288b355531e/tumblr_inline_mrwgxmWxuk1qz4rgp.gif",
  "https://i.imgur.com/GskRIXR.gif",
  "https://d1w5usc88actyi.cloudfront.net/wp-content/uploads/2013/08/FStoppers_Persistance-of-Vision_GaryMartin.gif",
  "https://i.imgur.com/SJxHr.gif",
  // "https://lh5.googleusercontent.com/-XCTjn-jhIqs/UaLjrDBOd-I/AAAAAAAA8Zk/tO59vWpGfKI/w426-h240/photo.jpg",
  "https://i.imgur.com/vX8lozU.gif",
  // "https://f.cl.ly/items/3f2P2T2T2k0p3K0R0N2H/Screen%20Shot%202013-09-05%20at%204.27.49%20PM.png",
  "https://i.imgur.com/jTQ0gbh.gif",
  "https://i.imgur.com/NW0mK39.gif",
  "https://i.imgur.com/NYFd64r.gif",
  "https://i.imgur.com/mc1SHbe.gif",
  "https://i.imgur.com/4003cn5.gif",
  "https://i.imgur.com/aTCokPU.gif",
  "https://i.imgur.com/mnRN5O4.gif",
  "https://i.imgur.com/emBDw7S.gif",
  "https://i.imgur.com/XQiErrk.gif",
  "https://i.imgur.com/davQLBo.gif",
  "https://i.imgur.com/KZwLV4q.gif",
  "https://i.imgur.com/szTQ7dL.gif",
  "https://i.imgur.com/bMq9APc.gif",
  "https://i.imgur.com/bsdz2KK.gif",
  "https://i.imgur.com/9DMQ7ae.gif",
  "https://i.imgur.com/3yEmUFm.gif",
  "https://i.imgur.com/nYuVFMI.gif",
  "https://i.imgur.com/iagYykI.gif",
  "https://i.imgur.com/l6Xgvsw.gif",
  "https://i.imgur.com/v745rRo.gif",
  "https://i.imgur.com/UvOtdLp.gif",
  "https://i.imgur.com/KSnHY7G.gif",
  "https://i.imgur.com/MfM8hEp.gif",
  "https://i.imgur.com/jlYFK9M.gif",
  "https://i.imgur.com/9SA7eYu.gif",
  "https://i.imgur.com/gkKviRB.gif",
  "https://i.imgur.com/vyf4HMz.gif",
  "https://i.imgur.com/zb3BZCv.gif",
  "https://i.imgur.com/OkLajvJ.gif",
  "https://i.imgur.com/nIfIO7B.gif",
  "https://i.imgur.com/vIcTXLB.gif",
  "https://i.imgur.com/297G0Yv.gif",
  "https://i.imgur.com/nchNwU3.gif",
  "https://i.imgur.com/fpLeJ72.gif",
  "https://i.imgur.com/dgxOC3t.gif",
  "https://i.imgur.com/fGhMmCL.gif",
  "https://i.imgur.com/HfCURPU.gif",
  "https://i.imgur.com/ef2dwkL.gif",
  "https://i.imgur.com/gFJuRrl.gif",
  "https://i.imgur.com/Evb2Bp4.gif",
  "https://i.imgur.com/CK3nE4D.gif",
  "https://i.imgur.com/Jq4KaUG.gif",
  "https://i.imgur.com/6TEKENJ.gif",
  "https://i.imgur.com/NAPUn0w.gif",
  "https://i.imgur.com/Bb5NN1w.gif",
  "https://i.imgur.com/nHwQ9OT.gif",
  "https://i.imgur.com/VYuxVse.gif",
  "https://i.imgur.com/6uecfLq.gif",
  "https://i.imgur.com/ISBUJSa.gif",
  "https://i.imgur.com/DJquD23.gif",
  "https://i.imgur.com/1Ccd5n0.gif",
  "https://i.imgur.com/XwFBDKm.gif",
  "https://i.imgur.com/3XOka2Q.gif",
  "https://i.imgur.com/QOQpPVE.gif",
  "https://i.imgur.com/xObqCPy.gif",
  "https://i.imgur.com/2wuFCho.gif",
  "https://i.imgur.com/JstVZOW.gif",
  "https://i.imgur.com/DBUrN4R.gif",
  "https://i.imgur.com/4FCpx4v.gif",
  "https://i.imgur.com/uM4SUXw.gif",
  "https://i.imgur.com/VIZgdxy.gif",
  "https://i.imgur.com/plr4DLd.gif",
  "https://i.imgur.com/oUMTTo6.gif",
  "https://i.imgur.com/soizCaY.gif",
  "https://i.imgur.com/MHWLac7.gif",
  "https://i.imgur.com/DYdqBOQ.gif",
  "https://i.imgur.com/vvTgHde.gif",
  "https://i.imgur.com/zW8idqj.gif",
  "https://i.imgur.com/3N0WPfx.gif",
  "https://i.imgur.com/PoykWUB.gif",
  "https://i.imgur.com/5zYBvoG.gif",
  "https://i.imgur.com/ew96NXw.gif",
  "https://i.imgur.com/zHwm2Hd.gif",
  "https://i.imgur.com/M4xObqC.gif",
  "https://i.imgur.com/OACf5cL.gif",
  "https://i.imgur.com/crVIR49.gif",
  "https://i.imgur.com/xZVyi5Y.gif",
  "https://i.imgur.com/eET8MpF.gif",
  "https://i.imgur.com/tjVOWZY.gif",
  "https://i.imgur.com/DO2WA2J.gif",
  "https://i.imgur.com/vnkglbw.gif",
  "https://i.imgur.com/igo4KsE.gif",
  "https://i.imgur.com/TH2b3rL.gif",
  "https://i.imgur.com/TaNTKki.gif",
  "https://i.imgur.com/zwKZz3E.gif",
  "https://i.imgur.com/OtcZb45.gif",
  "https://i.imgur.com/GLGo5yp.gif",
  "https://i.imgur.com/rGqnZJ0.gif",
  "https://i.imgur.com/yMLAGVx.gif",
  "https://i.imgur.com/WUTwNk9.gif",
  "https://i.imgur.com/6VFWhnV.gif",
  "https://i.imgur.com/jcYekhr.gif",
  "https://i.imgur.com/0cvffgS.gif",
  "https://i.imgur.com/e2T6sC4.gif",
  "https://i.imgur.com/ZvU6f2D.gif",
  "https://i.imgur.com/tQie8G2.gif",
  "https://i.imgur.com/VNfw0A4.gif",
  "https://i.imgur.com/7OVOjLj.gif",
  "https://i.imgur.com/1KPE3pG.gif",
  "https://i.imgur.com/doJRA0o.gif",
  "https://i.imgur.com/4MXcEuf.gif",
  "https://i.imgur.com/NzKeyiF.gif",
  "https://i.imgur.com/A46xD3Q.gif",
  "https://i.imgur.com/IZDzEBK.gif",
  "https://i.imgur.com/YsRzL3G.gif",
  "https://i.imgur.com/PJBO5VI.gif",
  "https://i.imgur.com/njPhhkc.gif",
  "https://i.imgur.com/6dCgyuo.gif",
  "https://i.imgur.com/z2AvXVG.gif",
  "https://i.imgur.com/mbCpvZD.gif",
  "https://i.imgur.com/FUiXiUm.gif",
  "https://i.imgur.com/VgyviMt.gif",
  "https://i.imgur.com/demDJGv.gif",
  "https://i.imgur.com/VoBp08Q.gif",
  "https://i.imgur.com/Jbm6lgm.gif",
  "https://i.imgur.com/wUNsNFR.gif",
  "https://i.imgur.com/zokplyL.gif",
  "https://i.imgur.com/JYQiziW.gif",
  "https://i.imgur.com/jxoPOUx.gif",
  "https://i.imgur.com/klSRmXk.gif",
  "https://i.imgur.com/E4nU7qj.gif",
  "https://i.imgur.com/VlRvQl8.gif",
  "https://i.imgur.com/wA908AV.gif",
  "https://i.imgur.com/TYttEQo.gif",
  "https://i.imgur.com/LRzylLj.gif",
  "https://www.themarysue.com/wp-content/uploads/2013/09/gif.gif",
  "https://i.imgur.com/ODKFb5N.gif",
  "https://i.imgur.com/mMY37yd.gif",
  "https://www.shamusyoung.com/twentysidedtale/images/gr12_shoot2.gif",
  "https://www.shamusyoung.com/twentysidedtale/images/gr13_walk.gif",
  "https://i.imgur.com/MAeDGcS.gif",
  "https://media.giphy.com/media/ISQjbZQtMv44g/200.gif",
  // "https://img.gawkerassets.com/img/190k5az7fagv7gif/original.gif",
  "https://i.imgur.com/KRkRW2b.gif",
  "https://i.imgur.com/5GYyMZO.gif",
  "https://i.imgur.com/XTFaPyG.gif",
  "https://www.thisiscolossal.com/wp-content/uploads/2013/07/night-1.gif",
  "https://i.imgur.com/ra7Ux6H.gif",
  "https://forgifs.com/gallery/d/212346-1/Greedy-cat-steals-food-bowl.gif",
  "https://i.imgur.com/pEpRff4.gif",
  "https://i.imgur.com/OJJMc5o.gif",
  "https://wmprofile-service-staging.s3.amazonaws.com/gifs/QC4Eu67O239FFXX0dnVe4xBA.gif",
  "https://i.imgur.com/zDUS6zP.gif",
  "https://cl.ly/image/263W0R2W3U0R/o",
  "https://i.imgur.com/ohB4y2j.gif",
  // "https://img.gawkerassets.com/img/192jqmrqshrapgif/original.gif",
  "https://media.giphy.com/media/BjCMpaEqFpIfC/giphy.gif",
  "https://i.imgur.com/TeR9Q5x.jpg",
  "https://img-9gag-fun.9cache.com/photo/aXbYWzz_460sa.gif",
  "https://media.tumblr.com/451b7d0fc068c6d5d77e7fb6b3e9407d/tumblr_muo55jb4111r2geqjo1_500.gif",
  // "https://lh6.googleusercontent.com/-xMf9T1kblxU/UmCTyL65V1I/AAAAAAAAC-U/9ISOUR7WqK8/w426-h303/IMG_0856.gif",
  // "https://images.dailydawdle.com/im-stuck-dog.gif",
  "https://i0.kym-cdn.com/photos/images/newsfeed/000/587/260/085.gif",
  "https://media.boingboing.net/wp-content/uploads/2013/10/chain.gif",
  "https://i.imgur.com/lSjkmNj.gif",
  "https://i.imgur.com/0AZnj2E.gif",
  // Shytrain prototype GIF
  "https://media.tumblr.com/4dbe147750e3e2934672e85ba19f0778/tumblr_mt6i57gmHW1sfo4yxo1_400.gif",
  "https://i.imgur.com/Fk1O108.gif",
  "https://i.imgur.com/iS6d6Tw.gif",
  "https://i.imgur.com/LDTayGL.gif",
  "https://i.imgur.com/ACNFaSa.gif",
  "https://i.imgur.com/NAvmfiO.gif",
  "https://i.imgur.com/cKUOhn3.gif",
  "https://i.imgur.com/NwQGoIz.gif",
  "https://i.imgur.com/EgqKgDu.gif",
  "https://i.imgur.com/ykHGabW.gif",
  "https://i.imgur.com/4DuH84y.gif",
  "https://i.imgur.com/omaYT10.gif",
  "https://i.imgur.com/GFgV5sX.gif",
  "https://i.imgur.com/piIho6d.gif",
  "https://i.imgur.com/VClw1Ba.gif",
  "https://i.imgur.com/hyAaSPb.png",
  // "https://zero.seanmartell.com/given.gif",
  "https://i.imgur.com/E1MwWI7.gif",
  "https://i.imgur.com/mZK4q8A.gif",
  "https://i2.kym-cdn.com/photos/images/original/000/634/126/bec.gif",
  "https://i.imgur.com/0E7omqu.gif",
  // "https://i.makeagif.com/media/3-21-2013/peXPCy.gif",
  "https://i.imgur.com/h1sIeqN.gif",
  // "https://img.gawkerassets.com/img/18y7cyzk17ukrgif/ku-large.gif",
  "https://i.imgur.com/nWDo91O.gif",
  "https://dribbble.s3.amazonaws.com/users/6410/screenshots/1254439/form-animation-_gif_.gif",
  "https://i.imgur.com/LLhDnmC.gif",
  "https://i.imgur.com/oyLFzOL.gif",
  "https://i.imgur.com/mm6WxQC.gif",
  "https://i.imgur.com/DysYwY8.gif",
  "https://i.imgur.com/Kd6PaBi.gif",
  "https://i.imgur.com/lJ5KEUm.gif",
  "https://i.imgur.com/YUujz9p.gif",
  "https://i.imgur.com/NqYlzzF.gif",
  "https://i.imgur.com/OjIwkv5.gif",
  "https://i.imgur.com/m0TClYC.gif",
  "https://static.squarespace.com/static/50085c8784aeae82b8acaca2/t/50b142f6e4b05036d3ad4ab3/1353794295993/attack01_03.gif",
  "https://lh3.googleusercontent.com/-TjctCmNwOkY/Un0JYrGPhaI/AAAAAAAADQk/BnCU6P9LEls/w626-h834-no/IMG_0530-MOTION.gif",
  "https://i.imgur.com/NCfuSRg.gif",
  "https://i.imgur.com/vZVlxnu.gif",
  "https://i.imgur.com/rNzOBFE.gif",
  "https://www.lordofweasels.net/files/0_e9e57_b9a220e2_orig.gif",
  "https://i.imgur.com/funpOFI.gif",
  "https://i.imgur.com/c9Ups.gif",
  "https://i.imgur.com/PuGoP.gif",
  "https://i.imgur.com/cRAAl.gif",
  "https://i.imgur.com/YXbpwdZ.gif",
  "https://i.imgur.com/uAW9O.gif",
  "https://i.imgur.com/OqvBYN4.gif",
  "https://i.imgur.com/h8gGpDP.gif",
  "https://www.reactiongifs.com/wp-content/uploads/2013/11/track-and-fail.gif",
  "https://i.imgur.com/pDO1anT.gif",
  "https://farm1.staticflickr.com/10/12433696_30eef32b4e_z.jpg",
  "https://frankchimero.com/writing/what-screens-want/images/burke17.gif",
  "https://frankchimero.com/writing/what-screens-want/images/muybridgeanimated.gif",
  "https://media.tumblr.com/eba75a4b1b81f8e82adb3d6b665cf6fb/tumblr_mvtif2eent1qdlh1io1_r1_400.gif",
  "https://i.imgur.com/jjMZakx.gif",
  "https://i.imgur.com/w48WIan.gif",
  "https://i.imgur.com/YiwxQKy.gif",
  "https://media.tumblr.com/f1d8af4bde8e72971b58383a041c6c73/tumblr_mx3i44y9g31s1le69o1_400.gif",
  "https://media.tumblr.com/8a19d8102e0d7135617cb1807253d9a1/tumblr_mwu2ubCNIa1r13l3bo10_500.gif",
  "https://media.tumblr.com/ca28fd0d6e740b738ba5a6acf5ef1aa0/tumblr_mx0mxgmeQp1qzt4vjo1_500.gif",
  "https://media.tumblr.com/878870d0cd05b7cdb7b03f80b94d93cb/tumblr_mgcp40vrV01qbn7n2o1_400.gif",
  "https://media.tumblr.com/09c91c59d02d2b379b9534d606b91b5d/tumblr_mtig1rhvvF1qbn7n2o1_400.gif",
  "https://i.imgur.com/9eh8pgT.gif",
  "https://i.imgur.com/8JAvbGO.gif",
  "https://i.imgur.com/wQi2FF9.gif",
  "https://i.imgur.com/LJjCyb9.gif",
  "https://i.imgur.com/3POyupA.gif",
  "https://i.imgur.com/NSxU6zi.gif",
  "https://i.imgur.com/vzQ3TeD.gif",
  "https://i.imgur.com/hLCoc9I.gif",
  "https://i.imgur.com/vq89XtV.gif",
  "https://i.imgur.com/2ZCfTOg.gif",
  "https://i.imgur.com/Rok67rS.gif",
  "https://i.imgur.com/B3zc2AZ.gif",
  "https://i.imgur.com/YnSVcOK.gif",
  "https://i.imgur.com/GtE549R.gif",
  "https://i.imgur.com/l3253mP.gif",
  "https://i.imgur.com/gYPpsF2.gif",
  "https://media.tumblr.com/e3efe6804fefbd96d40e8cb2f6c353ff/tumblr_inline_mylvs78a6H1s4zizu.gif",
  "https://i.imgur.com/GSqXDdK.jpg",
  "https://i.imgur.com/t3uPDUR.gif",
  "https://i.imgur.com/2bpCDs2.gif",
  "https://i.imgur.com/oNlTgVO.gif",
  "https://i.imgur.com/CX2AryG.gif",
  "https://i.imgur.com/tVOsz.gif",
  "https://i.imgur.com/WtyfMKq.gif",
  "https://i.imgur.com/RjloaY8.gif",
  // "https://img.gawkerassets.com/img/19d5kfuw3shqqgif/original.gif",
  "https://i.imgur.com/J12HOFt.gif",
  "https://i.imgur.com/qkNqNaF.gif",
  "https://i.imgur.com/nB3xyas.gif",
  // "https://dl.dropboxusercontent.com/u/2301433/Screenshots/bookmark-star.gif",
  "https://i.imgur.com/nMmCOEX.gif",
  "https://i.imgur.com/NnqzEeA.gif",
  "https://i.imgur.com/GpzeywR.gif",
  "https://i.chzbgr.com/maxW500/5742915328/h918ADF3E/",
  // "https://lh6.googleusercontent.com/-e-GF2t6pPZ4/UtY5DGAX1lI/AAAAAAAAZxU/XTm8f9nwkVM/w852-h480/oC8j4Kn.gif",
  "https://i.imgur.com/lz7hOlC.gif",
  "https://media.boingboing.net/wp-content/uploads/2014/01/sheep.gif",
  "https://i.imgur.com/kWG9Um9.gif",
  "https://i.imgur.com/0NysV2K.gif",
  "https://i.imgur.com/OCL4gko.gif",
  "https://i.imgur.com/DM8Zk4Z.gif",
  "https://i.imgur.com/hyejGaE.gif",
  "https://i.imgur.com/DBt8Zkd.gif",
  "https://forgifs.com/gallery/d/215762-1/Curveball-pitches.gif",
  "https://imgur.com/PYiP4gk",
  "https://i.imgur.com/vsl7NHo.gif",
  "https://i.imgur.com/I7mT0CS.gif",
  "https://i.imgur.com/jy7tE4t.gif",
  "https://i.imgur.com/mHPUpHo.gif",
  "https://i.imgur.com/SlRlzK3.gif",
  "https://i.imgur.com/TruG9B8.gif",
  "https://i.imgur.com/k9a4dhz.gif",
  "https://i.imgur.com/sE8Pvk2.gif",
  "https://i.imgur.com/WeBY6Qr.jpg",
  "https://1.bp.blogspot.com/-ES8PEHXEjqo/URKyMYcppKI/AAAAAAAAJdA/LYoWQwsl_60/s1600/ketchup-bottle.gif",
  "https://i.imgur.com/Bt3qlPZ.gif",
  "https://i.imgur.com/JHCjLB0.gif",
  // "https://geekslop.com/main/wp-content/uploads/2013/01/5537_0d02.gif",
  "https://i.imgur.com/MK7a0hq.gif",
  "https://www.jwz.org/images/312.gif",
  "https://media2.giphy.com/media/unzR48isp6cCY/giphy.gif",
  "https://media.giphy.com/media/IC3sfeqVlgW3K/giphy.gif",
  "https://i.imgur.com/dhm4v9t.gif",

  "https://i.imgur.com/tVjLxnv.gif",
  "https://i.chzbgr.com/maxW500/8142808320/h42365316/",
  "https://i.imgur.com/tVdttdG.gif",
  "https://i.imgur.com/arPNr.jpg",
  // "https://lh6.googleusercontent.com/-VmP8eWMO-xw/UzjikagOPVI/AAAAAAAAhsk/s4AMNToTmPE/w822-h465-no/IMAG0002_BURST001-MOTION.gif",
  // "https://f.cl.ly/items/2I1Z323M3x301z0o1Z0V/madhava3.gif",
  // "https://people-mozilla.org/~smartell/australis/tab-ux-1.gif",
  // "https://people-mozilla.org/~smartell/australis/tab-ux-2.gif",
  // "https://people-mozilla.org/~smartell/australis/tab-ux-3.gif",
  "https://i.imgur.com/pzflXnp.gif",
  "https://i.imgur.com/ikIUgC7.gif",

  // Moving hosted.akibraun.com images to imgur bc $$$
  // <3 aki
  "https://i.imgur.com/ADJIUFj.gif",
  "https://i.imgur.com/2Abd73O.gif",
  "https://i.imgur.com/rAVRXCH.gif",
  "https://i.imgur.com/CKXAJfF.gif",
  "https://i.imgur.com/0nrUM1Z.gif",
  "https://i.imgur.com/vzStuyN.gif",
  "https://i.imgur.com/F1sNOEX.gif",
  "https://i.imgur.com/3zUX2cs.gif",
  "https://i.imgur.com/JgEjbwc.gif",
  "https://i.imgur.com/9U6iu51.gif",
  "https://i.imgur.com/aY0iVQA.gif",
  "https://i.imgur.com/djHRiyw.gif",
  "https://i.imgur.com/RdFEiby.gif",
  "https://i.imgur.com/TwNBlMy.gif",
  "https://i.imgur.com/FAUiPhW.gif",
  "https://i.imgur.com/I1Y6eDu.gif",
  "https://i.imgur.com/YySzBZa.gif",
  "https://i.imgur.com/PpI0DPe.gif",
  "https://i.imgur.com/o3jP9bD.gif",
  "https://i.imgur.com/8zzZCM7.gif",
  "https://i.imgur.com/G5sOApM.gif",
  "https://i.imgur.com/gS3ThlP.gif",
  "https://i.imgur.com/E2N9svO.gif",
  "https://i.imgur.com/ePoqR5J.gif",
  "https://i.imgur.com/HsralnZ.gif",
  "https://i.imgur.com/guOclrH.gif",
  "https://i.imgur.com/JubxLku.gif",
  "https://i.imgur.com/PjnJrOw.gif",
  "https://i.imgur.com/EwZOf5C.gif",
  "https://i.imgur.com/P8fVE5j.gif",
  "https://i.imgur.com/61WHA7S.gif",
  "https://i.imgur.com/iCH0glt.gif",
  "https://i.imgur.com/7C2iHfV.gif",
  "https://i.imgur.com/YZMH9uO.gif",
  "https://i.imgur.com/F0eT5AK.gif",
  "https://i.imgur.com/w3OGwAm.gif",
  "https://i.imgur.com/h0FhzUo.gif",
  "https://i.imgur.com/zmWYKwG.gif",
  "https://i.imgur.com/iuDQeCa.gif",
  "https://i.imgur.com/J4RpO3e.gif",
  "https://i.imgur.com/t0dMUYX.gif",
  "https://i.imgur.com/Ig72DyY.gif",
  "https://i.imgur.com/JfIEF7I.gif",
  "https://i.imgur.com/u3OOOeH.gif",
  "https://i.imgur.com/6qu6s1j.gif",
  "https://i.imgur.com/pK8drBp.gif",
  "https://i.imgur.com/ki79PrV.gif",
  "https://i.imgur.com/iLBszGy.gif",
  "https://i.imgur.com/5K8BUKv.gif",
  "https://i.imgur.com/5FdDRnG.gif",
  "https://i.imgur.com/2nSRYfU.gif",
  "https://i.imgur.com/lQiGkq2.gif",
  "https://i.imgur.com/NAafVhV.gif",
  "https://i.imgur.com/IniuVQ5.gif",
  "https://i.imgur.com/LZcraw2.gif",
  "https://i.imgur.com/a52fkNS.gif",
  "https://i.imgur.com/DjiqJ32.gif",
  "https://i.imgur.com/yjPwYWP.gif",
  "https://i.imgur.com/Kb6RJ91.gif",
  "https://i.imgur.com/YDEFGUy.gif",
  "https://i.imgur.com/QHjBxjD.gif",
  "https://i.imgur.com/EeXUE6y.gif",
  "https://i.imgur.com/YN9HxAV.gif",
  "https://i.imgur.com/OjegCpk.gif",
  "https://i.imgur.com/6cmyaNu.gif",
  "https://i.imgur.com/OX6tZQo.gif",
  "https://i.imgur.com/zia1Jki.gif",
  "https://i.imgur.com/kngsTcW.gif",
  "https://i.imgur.com/Efo2GXU.gif",
  "https://i.imgur.com/hEcJ7qV.gif",
  "https://i.imgur.com/LqzFlgU.gif",
  "https://i.imgur.com/kRFxcR1.gif",
  "https://i.imgur.com/2WzWDeN.gif",
  "https://i.imgur.com/VGaG7Gy.gif",
  "https://i.imgur.com/bFZTz3a.gif",
  "https://i.imgur.com/W8tcXdi.gif",
  "https://i.imgur.com/LfqD9PN.gif",
  "https://i.imgur.com/sKip59b.gif",
  "https://i.imgur.com/4iNuMMv.gif",
  "https://i.imgur.com/8EX2alU.gif",
  "https://i.imgur.com/KNHaKlA.gif",
  "https://i.imgur.com/HggSbFO.gif",
  "https://i.imgur.com/Xl6g5zz.gif",
  "https://i.imgur.com/7KcmdwC.gif",
  "https://i.imgur.com/woTbFAB.gif",
  "https://i.imgur.com/S0Mql3T.gif",
  "https://i.imgur.com/84zwTat.gif",
  "https://i.imgur.com/7Qx08Ai.gif",
  "https://i.imgur.com/VOb3ieN.gif",
  "https://i.imgur.com/LaIviDI.gif",
  "https://i.imgur.com/6REjS39.gif",
  "https://i.imgur.com/aOhui2h.gif",
  "https://i.imgur.com/LYN4WFJ.gif",
  "https://i.imgur.com/a81mUu7.gif",
  "https://i.imgur.com/TD3fTUv.gif",
  "https://i.imgur.com/Uwz9zgn.gif",
  "https://i.imgur.com/nPgqJJz.gif",
  "https://i.imgur.com/3pEELXd.gif",
  "https://i.imgur.com/SSfNBkh.gif",
  "https://i.imgur.com/wZlJP6s.gif",
  "https://i.imgur.com/FJlGuW1.gif",
  "https://i.imgur.com/IojPcdf.gif",
  "https://i.imgur.com/x3f7H4j.gif",
  "https://i.imgur.com/qopnNEh.gif",
  "https://i.imgur.com/ILy1hbE.gif",
  "https://i.imgur.com/DuE0Blb.gif",
  "https://i.imgur.com/YMPQewR.gif",
  "https://i.imgur.com/jySRkKP.gif",
  "https://i.imgur.com/YPL4eoQ.gif",
  "https://i.imgur.com/o2x8EZU.gif",
  "https://i.imgur.com/S8IJjqY.gif",
  "https://i.imgur.com/wYlaLee.gif",
  "https://i.imgur.com/T3laXzx.gif",
  "https://i.imgur.com/QhbP10b.gif",
  "https://i.imgur.com/IbWZRFI.gif",
  "https://i.imgur.com/zhTMbSo.gif",
  "https://i.imgur.com/2NTqTS5.gif",
  "https://i.imgur.com/jeqr1Wv.gif",
  "https://i.imgur.com/6lC8U3w.gif",
  "https://i.imgur.com/Ec9EeEM.gif",
  "https://i.imgur.com/AKzD9Qi.gif",
  "https://i.imgur.com/znHHzSl.gif",
  "https://i.imgur.com/oYlHTR8.gif",
  "https://i.imgur.com/ehQo7VO.gif",
  "https://i.imgur.com/vfY4LRE.gif",
  "https://i.imgur.com/mSKyNjz.gif",
  "https://i.imgur.com/ePY1AFD.gif",
  "https://i.imgur.com/7WjNa9t.gif",
  "https://i.imgur.com/aI54AaQ.gif",
  "https://i.imgur.com/NPFmNXE.gif",
  "https://i.imgur.com/CAldxx9.gif",
  "https://i.imgur.com/M7Mxoe9.gif",
  "https://i.imgur.com/45eMYUd.gif",
  "https://i.imgur.com/6wRO4D9.gif",
  "https://i.imgur.com/xM9tlDL.gif",
  "https://i.imgur.com/ULpTZzP.gif",
  "https://i.imgur.com/gMCKxwz.gif",
  "https://i.imgur.com/MUS5PO0.gif",
  "https://i.imgur.com/95CLguj.gif",
  "https://i.imgur.com/yaRBUoV.gif",
  "https://i.imgur.com/OFRJ5sL.gif",
  "https://i.imgur.com/wl4YDMu.gif",
  "https://i.imgur.com/vI4UCcq.gif",
  "https://i.imgur.com/OC1sVlf.gif",
  "https://i.imgur.com/uMlioSq.gif",
  "https://i.imgur.com/mA9ADT6.gif",
  "https://i.imgur.com/KtHKQlA.gif",
  "https://i.imgur.com/c99WPMZ.gif",
  "https://i.imgur.com/A0PZQ4j.gif",
  "https://i.imgur.com/gLoSfGD.gif",
  "https://i.imgur.com/3i6NEmo.gif",
  "https://i.imgur.com/AyEeTuN.gif",
  "https://i.imgur.com/tjmaiv8.gif",
  "https://i.imgur.com/CnBhMZq.gif",
  "https://i.imgur.com/4DPzLHF.gif",
  "https://i.imgur.com/8xGgb86.gif",
  "https://i.imgur.com/FffN4B5.gif",
  "https://i.imgur.com/b1405aP.gif",
  "https://i.imgur.com/Ll2CY19.gif",
  "https://i.imgur.com/8wix3VP.gif",
  "https://i.imgur.com/xnLIl5B.gif",
  "https://i.imgur.com/pUGq3Mp.gif",
  "https://i.imgur.com/SVTWLsS.gif",
  "https://i.imgur.com/WhvSRGd.gif",
  "https://i.imgur.com/AEjROF2.gif",
  "https://i.imgur.com/Tfjy1QL.gif",
  "https://i.imgur.com/bf8bzYn.gif",
  "https://i.imgur.com/VVSeROL.gif",
  "https://i.imgur.com/seFsO18.gif",
  "https://i.imgur.com/Z04ZMtb.gif",
  "https://i.imgur.com/a5HkHCF.gif",
  "https://i.imgur.com/r1hp2vA.gif",
  "https://i.imgur.com/9opCfNn.gif",
  "https://i.imgur.com/4ErLb5N.gif",
  "https://i.imgur.com/I9CM77N.gif",
  "https://i.imgur.com/JGtdWMZ.gif",
  "https://i.imgur.com/rF6FjIY.gif",
  "https://i.imgur.com/phbmrOv.gif",
  "https://i.imgur.com/OyTOGt7.gif",
  "https://i.imgur.com/SkfmXkc.gif",
  "https://i.imgur.com/vY6V4jI.gif",
  "https://i.imgur.com/lqVYQkh.gif",
  "https://i.imgur.com/L3bX6oX.gif",
  "https://i.imgur.com/31bItDK.gif",
  "https://i.imgur.com/e3A5YqO.gif",
  "https://i.imgur.com/aaOJXeY.gif",
  "https://i.imgur.com/oJ7gND4.gif",
  "https://i.imgur.com/q4ViuzF.gif",
  "https://i.imgur.com/foiGftY.gif",
  "https://i.imgur.com/PDfQwi3.gif",
  "https://i.imgur.com/cl9MvDK.gif",
  "https://i.imgur.com/zVSZmFR.gif",
  "https://i.imgur.com/Keno4BJ.gif",
  "https://i.imgur.com/9Foxz9C.gif",
  "https://i.imgur.com/zIZ1uXM.gif",
  "https://i.imgur.com/e2LEYwT.gif",
  "https://i.imgur.com/W9lUlJS.gif",
  "https://i.imgur.com/5oKyFjR.gif",
  "https://i.imgur.com/a8JtSRV.gif",
  "https://i.imgur.com/aScyPWq.gif",
  "https://i.imgur.com/fwLknXm.gif",
  "https://i.imgur.com/m6zr5dM.gif",
  "https://i.imgur.com/tgzOz7e.gif",
  "https://i.imgur.com/5GuD4eq.gif",
  "https://i.imgur.com/PG8Nxqq.gif",
  "https://i.imgur.com/F6vE6KR.gif",
  "https://i.imgur.com/gkpYIpu.gif",
  "https://i.imgur.com/vUMN248.gif",
  "https://i.imgur.com/JKWFMDo.gif",
  "https://i.imgur.com/dv4KSuK.gif",
  "https://i.imgur.com/hVLUnn1.gif",
  "https://i.imgur.com/X6fe5kV.gif",
  "https://i.imgur.com/wavHf5K.gif",
  "https://i.imgur.com/e0JhO8K.gif",
  "https://i.imgur.com/WyC0i4R.gif",
  "https://i.imgur.com/a7HGA50.gif",
  "https://i.imgur.com/2LkLpUp.gif",
  "https://i.imgur.com/I4IjJ4S.gif",
  "https://i.imgur.com/RyGZ1du.gif",
  "https://i.imgur.com/1QHtQJV.gif",
  "https://i.imgur.com/k04Amig.gif",
  "https://i.imgur.com/yK3n9P2.gif",
  "https://i.imgur.com/gi7MWku.gif",
  "https://i.imgur.com/bEcwEOO.gif",
  "https://i.imgur.com/oX6ATtc.gif",
  "https://i.imgur.com/ZTIcAKw.gif",
  "https://i.imgur.com/xJ3WVLy.gif",
  "https://i.imgur.com/DjwmoVS.gif",
  "https://i.imgur.com/LCJJX6R.gif",
  "https://i.imgur.com/RrqLy14.gif",
  "https://i.imgur.com/eeoeH89.gif",
  "https://i.imgur.com/aK4aEXf.gif",
  "https://i.imgur.com/3owfVlo.gif",
  "https://i.imgur.com/AXQWX43.gif",
  "https://i.imgur.com/Wy4UEnx.gif",
  "https://i.imgur.com/7i8Ebxu.gif",
  "https://i.imgur.com/puc0H79.gif",
  "https://i.imgur.com/nWI8bYD.gif",
  "https://i.imgur.com/Pzg5l3g.gif",
  "https://i.imgur.com/Exhlkju.gif",
  "https://i.imgur.com/SM32SGe.gif",
  "https://i.imgur.com/gxT59jY.gif",
  "https://i.imgur.com/rirckjo.gif",
  "https://i.imgur.com/Z8oiQAc.gif",
  "https://i.imgur.com/e7Dt753.gif",
  "https://i.imgur.com/fhPMJYo.gif",
  "https://i.imgur.com/GmPPoDv.gif",
  "https://i.imgur.com/a0uT7Em.gif",
  "https://i.imgur.com/7cFXlCw.gif",
  "https://i.imgur.com/Oh0kas3.gif",
  "https://i.imgur.com/TPfT4DI.gif",
  "https://i.imgur.com/QtWL6qd.gif",
  "https://i.imgur.com/BUoDEcA.gif",
  "https://i.imgur.com/Ic72Mje.gif",
  "https://i.imgur.com/2ZmJUMX.gif",
  "https://i.imgur.com/CK6a7kT.gif",
  "https://i.imgur.com/ZcGtR3H.gif",
  "https://i.imgur.com/amiLFOt.gif",
  "https://i.imgur.com/RIJHOc4.gif",
  "https://i.imgur.com/406ZvdK.gif",
  "https://i.imgur.com/bS0ScRW.gif",
  "https://i.imgur.com/6ktWizV.gif",
  "https://i.imgur.com/vsokAqp.gif",
  "https://i.imgur.com/5vNYiMq.gif",
  "https://i.imgur.com/TUtjCv1.gif",
  "https://i.imgur.com/ok658an.gif",
  "https://i.imgur.com/ht27UqN.gif",
  "https://i.imgur.com/A1lvOmC.gif",
  "https://i.imgur.com/MSVi2WN.gif",
  "https://i.imgur.com/cMlVnY0.gif",
  "https://i.imgur.com/UwigUGo.gif",
  "https://i.imgur.com/Ztw4ru4.gif",
  "https://i.imgur.com/rILwg9C.gif",
  "https://i.imgur.com/6I1NKl5.gif",
  "https://i.imgur.com/Fucpnzm.gif",
  "https://i.imgur.com/iEyero5.gif",
  "https://i.imgur.com/Pu6EUM9.gif",
  "https://i.imgur.com/dk56HrG.gif",
  "https://i.imgur.com/squTtmy.gif",
  "https://i.imgur.com/lJh03bI.gif",
  "https://i.imgur.com/bjD1hyb.gif",
  "https://i.imgur.com/h0fYmFu.gif",
  "https://i.imgur.com/eHW79BV.gif",
  "https://i.imgur.com/0k7y9Fz.gif",
  "https://i.imgur.com/XDDrH2P.gif",
  "https://i.imgur.com/5VUHQ22.gif",
  "https://i.imgur.com/sUnc0cR.gif",
  "https://i.imgur.com/q2X5uqH.gif",
  "https://i.imgur.com/Q3p9shH.gif",
  "https://i.imgur.com/7ehuodM.gif",
  "https://i.imgur.com/NDvpo25.gif",
  "https://i.imgur.com/4iJr4W9.gif",
  "https://i.imgur.com/xweqw5Q.gif",
  "https://i.imgur.com/veinYeB.gif",
  "https://i.imgur.com/pzmKmkX.gif",
  "https://i.imgur.com/B20haWu.gif",
  "https://i.imgur.com/sbsQjeX.gif",
  "https://i.imgur.com/GIvqvJu.gif",
  "https://i.imgur.com/dexWE04.gif",
  "https://i.imgur.com/HNFOQcN.gif",
  "https://i.imgur.com/rluDm5m.gif",
  "https://i.imgur.com/tXyhFoL.gif",
  "https://i.imgur.com/0nLTx8o.gif",
  "https://i.imgur.com/ckfo2k4.gif",
  "https://i.imgur.com/4caiGbN.gif",
  "https://i.imgur.com/eGxWIjF.gif",
  "https://i.imgur.com/BnJ9vuT.gif",
  "https://i.imgur.com/hCZIvHZ.gif",
  "https://i.imgur.com/j87zIzF.gif",
  "https://i.imgur.com/KwLgfRn.gif",
  "https://i.imgur.com/EZueaFO.gif",
  "https://i.imgur.com/Od2Tv9E.gif",
  "https://i.imgur.com/PFESuGX.gif",
  "https://i.imgur.com/A5OBn5W.gif",
  "https://i.imgur.com/qzWAXpN.gif",
  "https://i.imgur.com/5RQO89F.gif",
  "https://i.imgur.com/VfycMoS.gif",
  "https://i.imgur.com/8vGRO1h.gif",
  "https://i.imgur.com/k5ylJfo.gif",
  "https://i.imgur.com/Z5cB8tb.gif",
  "https://i.imgur.com/nqJOhdy.gif",
  "https://i.imgur.com/Tu1UrOv.gif",
  "https://i.imgur.com/XZdurWe.gif",
  "https://i.imgur.com/EUuKxjZ.gif",
  "https://i.imgur.com/WiZDWf5.gif",
  "https://i.imgur.com/LfSQT1N.gif",
  "https://i.imgur.com/rPuZpBY.gif",
  "https://i.imgur.com/7v09U7J.gif",
  "https://i.imgur.com/Q7oodmj.gif",
  "https://i.imgur.com/HUrTaWi.gif",
  "https://i.imgur.com/NuLZIqe.gif",
  "https://i.imgur.com/C4NG6mG.gif",
  "https://i.imgur.com/DvI4oK9.gif",
  "https://i.imgur.com/pVm4FSR.gif",
  "https://i.imgur.com/2QeM1TI.gif",
  "https://i.imgur.com/7DLoKd9.gif",
  "https://i.imgur.com/ltU8aRY.gif",
  "https://i.imgur.com/M99MCrW.gif",
  "https://i.imgur.com/pArzm7S.gif",
  "https://i.imgur.com/X0eFJ5J.gif",
  "https://i.imgur.com/KlEbo7N.gif",
  "https://i.imgur.com/2jDrAs2.gif",
  "https://i.imgur.com/93lnwRc.gif",
  "https://i.imgur.com/9ktfjzX.gif",
  "https://i.imgur.com/OCdrEZS.gif",
  "https://i.imgur.com/BpA9XIN.gif",
  "https://i.imgur.com/D4VXOED.gif",
  "https://i.imgur.com/pcxwzfI.gif",
  "https://i.imgur.com/kT8XpGK.gif",

  "https://i.imgur.com/nJnD26r.gif",
  "https://i.imgur.com/yGTWHjj.gif",
  "https://i.imgur.com/LNkJCwQ.gif",
  "https://media.tumblr.com/880322bf5787f6fdb2886ca0ec12c5a2/tumblr_n60h4l2IzH1s2yegdo1_400.gif",
  "https://i.imgur.com/RdZZnCH.gif",
  "https://i.imgur.com/ZWNzL51.gif",
  "https://i.imgur.com/ccEeYFH.gif",
  "https://i.imgur.com/rOqzFcB.gif",
  "https://i.imgur.com/pzOd5dM.gif",
  "https://i.imgur.com/H67NuBi.gif",
  "https://i.imgur.com/yyvlGKl.gif",
  "https://i.imgur.com/MCy8H1A.gif",
  "https://media.tumblr.com/8ade129ecd3cc2998f39df15190b4bac/tumblr_n4yoxn48IO1rtpfpio1_400.gif",
  "https://i.imgur.com/qwy5mtH.gif",
  "https://giant.gfycat.com/AbleAmbitiousBluetonguelizard.gif",
  "https://i.imgur.com/kFdf2kM.gif",
  "https://i.imgur.com/V4tUVQn.gif",
  "https://i.imgur.com/4A7Yolq.gif",
  // "https://f.cl.ly/items/2y2e07041V283c1I2G0S/mozheart.gif",
  "https://i.imgur.com/714mXxm.gif",
  "https://i.imgur.com/rpzfs.jpg",
  "https://i.imgur.com/E9tpawM.gif",
  "https://farm6.staticflickr.com/5194/14227992609_dc664747a7_o.gif",
  "https://assets.sbnation.com/assets/2683567/thepassion.gif",
  "https://media.tumblr.com/4bd1a6dcf1faf1005fe7a70119adb618/tumblr_n74yinoKIS1ru5h8co1_500.gif",
  "https://i.imgur.com/frnXxyM.gif",
  "https://media.tumblr.com/tumblr_m43t64L7sH1qz6ygbo1_500.gif",
  "https://i.imgur.com/AOrz56D.gif",
  "https://media.giphy.com/media/Mjyam3Hu41MPK/giphy.gif",
  "https://i.imgur.com/eJqeEtl.gif",
  "https://i.imgur.com/JjTg3u6.gif",
  "https://media.tumblr.com/2974d54f9f63515cff0a5b29f9fa35d2/tumblr_n8vhz0RJxs1qewacoo1_500.gif",
  "https://media.tumblr.com/tumblr_mbyv6a4lIC1r478p8o1_500.gif",
  "https://i.chzbgr.com/maxW500/8277665024/h4C1F0CB7/",
  "https://i.imgur.com/HL4jqNm.gif",
  "https://media.tumblr.com/9f02f2cd23f259e95ff57796e355aa75/tumblr_n8zzyojmX31rir0h2o1_250.gif",
  "https://i.imgur.com/0x9Twfu.gif",
  "https://i.imgur.com/SsmohWu.gif",
  "https://i.imgur.com/YmwCy0H.gif",
  "https://i.imgur.com/DMTxyk2.gif",
  "https://i.imgur.com/GaDmLMJ.gif",
  "https://i.imgur.com/QY0YEc3.gif",
  "https://i.imgur.com/6Q9FXQB.gif",
  "https://i.imgur.com/0ZLvC1p.gif",
  "https://i.imgur.com/n4AFVbw.gif",
  "https://i.imgur.com/rm8jGAQ.gif",
  "https://i.imgur.com/XRSzIh7.gif",
  // "https://images.apple.com/r/store/backsoon/1x-covers-animation-v3.gif",
  "https://media.tumblr.com/dbb193b999dededdea1aae46706bc2bf/tumblr_na8e02lWXw1qagaplo1_400.gif",
  "https://i.imgur.com/JTf2Mk6.gif",
  "https://media.tumblr.com/tumblr_m7oyiuMYum1r0ralmo1_500.gif",
  "https://i.imgur.com/6bOYx4b.gif",
  "https://i.imgur.com/85Pd59R.jpg",
  "https://i.imgur.com/3sRm90k.gif",
  "https://i.imgur.com/cNLoTtd.jpg",
  // "https://cdn.bgr.com/2014/09/iphones-unlock.gif",
  "https://i.imgur.com/UuedhQX.gif",
  "https://i.imgur.com/Rqr2nYd.gif",
  "https://media.giphy.com/media/ToMjGpn4gsN6bmeWhnq/giphy.gif",
  "https://i.imgur.com/XrqlOcL.jpg",
  "https://i.imgur.com/aEg7mMX.gif",
  "https://media.tumblr.com/1b4baf3553ac58c742b23fd0251704dc/tumblr_ndnc1pRfqE1ql8t12o2_r1_500.gif",
  // "https://static.celebuzz.com/uploads/2013/05/11/gatsby-leo-051113.gif",
  "https://i.imgur.com/rQJDggl.gif",
  "https://media-cache-ec0.pinimg.com/originals/10/5b/17/105b17fa77619b1e0216c23df334af28.jpg",
  "https://i.giphy.com/TeSh0CFqLvUpq.gif",
  "https://media.tumblr.com/19e053c1491fcf0b275b9bd39d175f0c/tumblr_neemq1BxD01r9mp00o1_500.gif",
  "https://i.chzbgr.com/maxW500/4607993088/hAFBE814D/",
  "https://media.giphy.com/media/t4lIagU8UJfYA/giphy.gif",
  "https://media.giphy.com/media/ngXo25cuhbQbe/giphy.gif",
  "https://media1.giphy.com/media/12b3E4U9aSndxC/giphy.gif",
  // "https://stream1.gifsoup.com/view/408294/french-bulldog-o.gif",
  "https://media.giphy.com/media/YaT2596iKOhnq/giphy.gif",
  "https://media.giphy.com/media/OyIZL9LYrwFJ6/giphy.gif",
  "https://media.tumblr.com/02559c8c1815a0d37479b10dff3f5fe7/tumblr_n900gl4U941qdlh1io1_400.gif",
  "https://media.tumblr.com/56d4c36462045ae0879092bd49db8065/tumblr_n7y44mp1jN1tchrkco1_500.gif",
  // "https://stream1.gifsoup.com/view5/20140719/5073433/computer-and-cat-o.gif",
  "https://i.imgur.com/TQoL8Fs.gif",
  "https://i.imgur.com/bnhj3.gif",
  "https://i.imgur.com/8qblYFN.gif",
  "https://i.imgur.com/JpX3fCQ.gif",
  "https://www.blogcdn.com/www.pawnation.com/media/2013/05/sun.gif",
  "https://i.imgur.com/0LdPDVa.gif",
  // "https://cuteoverload.files.wordpress.com/2013/04/yo-sup-cat-high-five.gif?w=560&h=357",
  "https://i.imgur.com/RQPGk18.gif",
  "https://i.imgur.com/EORdTfi.gif",
  "https://i.imgur.com/JC6iZ4k.gif",
  "https://media.tumblr.com/bf7e436e6707e5c968f5f74b658c4591/tumblr_mjxsftUvWz1qzujn9o1_400.gif",
  "https://i.imgur.com/noXjdoB.gif",
  // "https://media.tumblr.com/9e2a42cde3592705329e9e76c21b8dee/tumblr_mqx2xwWHOF1sd71suo1_400.gif",
  "https://i.imgur.com/ZkhZtCy.gif",
  "https://media.tumblr.com/tumblr_ljq967OCtR1qdaeo5o1_500.gif",
  "https://i.imgur.com/4PD98.gif",
  "https://media.tumblr.com/2e1b49f874296b65bd9ec0630d29b69d/tumblr_mnyhoka5OI1s9362xo1_400.gif",
  "https://i.imgur.com/ovOZuZQ.gif",
  "https://i.imgur.com/HYtnhnk.gif",
  "https://i.imgur.com/3Uxuj3e.gif",
  "https://images.fastcompany.com/upload/inline-1-cat-gif.gif",
  "https://i.imgur.com/fSSVQ70.gif",
  "https://i.imgur.com/Wvy6TD6.gif",
  "https://media.tumblr.com/tumblr_lxnj6anDMI1qj16xfo1_250.gif",
  "https://i.imgur.com/V6OwFem.gif",
  "https://media.tumblr.com/cdfb208d23bd6f0ff8e3bd59ebe0e848/tumblr_inline_mmrgssvFco1qz4rgp.gif",
  "https://i.imgur.com/OEyppE0.gif",
  "https://media.tumblr.com/339042f90037fcd98ca9341277f7fa1e/tumblr_mnqgldB5Le1sok7a0o1_400.gif",
  "https://media.tumblr.com/c2bc6de109c9f829cf92c0be11e9294b/tumblr_mr7nm4dlGa1qhnszoo1_400.gif",
  "https://lh3.ggpht.com/-R1xnbehvBvM/UYENyPF0LrI/AAAAAAAAiLg/nBPObGUHRsk/s1600/funny-cat-gifs-048-010.gif",
  "https://i.imgur.com/6J9qAye.gif",
  "https://media.tumblr.com/3001a8872eff95532084422a9e3bbb5e/tumblr_mgy502rNKi1radzayo1_250.gif",
  "https://i.imgur.com/9cv0ptk.jpg",
  "https://i.imgur.com/vpZk6kW.gif",
  "https://www.catgifpage.com/gifs/180.gif",
  "https://i.imgur.com/o5KRHee.gif",
  "https://media.tumblr.com/tumblr_mbeygfUCY31rxye79o1_250.gif",
  "https://i.imgur.com/gC9OPAq.gif",
  "https://i.imgur.com/Vm6Qqfe.gif",
  "https://i.imgur.com/yurTtSn.gif",
  "https://i.imgur.com/uHDzq2l.gif",
  "https://i.imgur.com/r8Wi5UC.gif",
  "https://i.imgur.com/ot7Yimy.gif",
  "https://i.imgur.com/ocReSPg.gif",
  "https://i.imgur.com/pJEMLpK.gif",
  "https://i.imgur.com/fTMrDe6.gif",
  "https://i.imgur.com/CZumVT0.gif",
  "https://i.imgur.com/z4T2iMJ.gif",
  "https://i.imgur.com/QZOc4oS.gif",
  "https://i.imgur.com/dyKQrYa.gif",
  "https://i.imgur.com/UxZRZ2i.gif",
  "https://i.imgur.com/JsJflTY.gif",
  "https://i.imgur.com/JOyUnB3.gif",
  "https://i.imgur.com/MPLRdMG.gif",
  "https://i.imgur.com/dEEDgvT.gif",
  "https://i.imgur.com/kozmIP9.gif",
  "https://i.imgur.com/SWGyk.gif",
  "https://i.imgur.com/8IbtpOR.gif",
  "https://i.imgur.com/N2RY5Xa.gif",
  "https://i.imgur.com/yx0fnvA.gif",
  "https://www.mycathatesyou.com/wp-content/gallery/gifs/8.gif",
  "https://i.imgur.com/RuopmXU.gif",
  "https://media.giphy.com/media/SrmLZIT3S8oFO/giphy.gif",
  // "https://lolsnaps.com/upload_pic/Mynewfavoritecatgif-47931.gif",
  "https://i.imgur.com/C1VMIYX.gif",
  "https://i.imgur.com/4sK7euh.gif",
  "https://media.giphy.com/media/XMvrleT9jksXm/giphy.gif",
  "https://media.tumblr.com/tumblr_lw63keBwD81qk10i8o1_500.gif",
  "https://i.imgur.com/XQ1AM07.gif",
  "https://i.imgur.com/8ZoawKz.gif",
  "https://i.imgur.com/nyiZZf7.gif",
  "https://i.kinja-img.com/gawker-media/image/upload/s--fh-7v3iN--/vgghvs5kvylabsbsumw5.gif",
  "https://i.giphy.com/PkRjXKSNU5ioM.gif",
  "https://media.tumblr.com/c9d8c587328c4e2a468fe3e050da65e0/tumblr_n5zo6bBwT71s96utdo1_400.gif",
  "https://media.tumblr.com/52841ae6e8f2c8516fd87b84e7c418be/tumblr_inline_n54glm8QLd1rgf79x.gif",
  "https://i.imgur.com/aJYZ20v.gif",
  "https://dl.dropboxusercontent.com/s/2xtuy519bonio44/happy-pokemon.gif",
  "https://dl.dropboxusercontent.com/s/wdk7iogol2p4atu/pikachuhaters.gif",
  "https://blog.codepen.io/wp-content/uploads/2014/12/shake.gif",
  "https://i.imgur.com/whjcDLZ.gif",
  "https://i.imgur.com/BNCrcEC.gif",
  "https://i.imgur.com/hcTUAjc.gif",
  "https://i.imgur.com/wEurzKw.gif",
  "https://i.imgur.com/3pFzXAS.gif",
  "https://i.imgur.com/fEeMuH8.gif",
  "https://media.tumblr.com/14c2af6a8b01906cbecec1cc6d9e5fc4/tumblr_ne6f0gDITT1qdlh1io1_500.gif",
  "https://giant.gfycat.com/JitteryPlushGrayfox.gif",
  "https://i.imgur.com/VOZaZZi.gif",
  "https://i.imgur.com/iqgIIwN.gif",
  "https://media0.giphy.com/media/nKN7E76a27Uek/200.gif",
  "https://i.imgur.com/EMMtZOv.gif",
  "https://i.imgur.com/x6QwaXJ.gif",
  "https://i.imgur.com/SlFnS9r.gif",
  "https://i.imgur.com/jLUAQuo.gif",
  // "https://dl.dropboxusercontent.com/u/124744/meme/dropmic.gif",
  "https://media.tumblr.com/9923249236711a3e4f7995df8ab57034/tumblr_n1b9mp4rWd1qht0ago1_400.gif",
  "https://media.tumblr.com/34f77a472899938f48aee0aff4e36432/tumblr_inline_ni76splLQI1s5ajcs.gif",
  "https://media.tumblr.com/31c44cfaea6e64be9e494887c6882af4/tumblr_inline_ni76t0DsuI1s5ajcs.gif",
  "https://media.tumblr.com/0c04093dff9c4e2c89bc782cac9804fe/tumblr_niskkjY1vJ1u0n985o1_500.gif",
  "https://media.tumblr.com/c762e870dbae0649b62fc3e24af06bed/tumblr_n7logsAUm71td3b95o1_500.gif",
  "https://media.tumblr.com/6ca1c08405d85101b5a3fa30264aad27/tumblr_n8jq10M2fQ1r2u47wo2_500.gif",
  "https://media.tumblr.com/19346776f46a84094178af7a7c4d281a/tumblr_n8jq10M2fQ1r2u47wo4_500.gif",
  "https://media.tumblr.com/2fba2b89d2a1b15e6493f0a9567e1e4e/tumblr_n8jq10M2fQ1r2u47wo5_500.gif",
  "https://media.tumblr.com/3706fa06d24015c22a2dc97981f5b897/tumblr_n8iko9sZCf1sbo963o1_r2_500.gif",
  "https://i.chzbgr.com/maxW500/8439079936/h9CAA73CF/",
  "https://media.tumblr.com/16b782a2ddd0bce38f5b6f85f2db3254/tumblr_n9kvm5bw3m1sh3xeyo6_400.gif",
  "https://media.tumblr.com/5a2ca013c42da858d2841cbc91b9c4bb/tumblr_n9kvm5bw3m1sh3xeyo4_400.gif",
  "https://media.tumblr.com/14ef68f0fd10d3c9784c6d3110dc966f/tumblr_n9kvm5bw3m1sh3xeyo3_400.gif",
  "https://media.tumblr.com/add4ff50565d4ceed1587f704df86a73/tumblr_n9kvm5bw3m1sh3xeyo2_400.gif",
  "https://media.tumblr.com/0f272e5453202d432f2e4a2bf7182006/tumblr_n9kvm5bw3m1sh3xeyo5_500.gif",
  "https://i.imgur.com/LTULmqF.gif",
  "https://media1.giphy.com/media/Hq2XDestpCXq8/giphy.gif",
  "https://media.tumblr.com/90686d424bd2d345d1b84ac810a66926/tumblr_inline_mnus57YdGf1qz4rgp.gif",
  "https://media.giphy.com/media/1mROAaaFoYtPO/giphy.gif",
  "https://i.imgur.com/Y6MD1Hk.gif",
  // "https://dl.dropboxusercontent.com/u/2301433/Do.gif",
  "https://media2.giphy.com/media/VfI6QrXqSJMyc/giphy.gif",
  "https://i.imgur.com/QNocJYG.gif",
  "https://i.imgur.com/ZYdQRH4.gif",
  "https://media.tumblr.com/6ec14d27acd06585cb7c7f625608368d/tumblr_njgu97BOhT1ql2w65o2_500.gif",
  "https://media.tumblr.com/a8b2dbf79c00ba1be50602cd7066cb6d/tumblr_njgu97BOhT1ql2w65o4_500.gif",
  // "https://img.pandawhale.com/44815-Hamster-SOON-Rutr.gif",
  "https://media.boingboing.net/wp-content/uploads/2015/02/snail.gif",
  "https://i.imgur.com/6mkmkFP.gif",
  "https://media.tumblr.com/7680eca1c073e0cc1498ae6fee48fdf3/tumblr_n0953mGjb11rpfx57o1_500.gif",
  "https://i.imgur.com/NSSDYLG.gif",
  "https://giant.gfycat.com/UnfitBlissfulArchaeopteryx.gif",
  "https://media.tumblr.com/00caa232be1e80ae306f2a20325b0ba9/tumblr_n9qwx5pSMq1ri3ih0o1_500.gif",
  "https://media.tumblr.com/3737ed101e8dd5bd585afda8d9c25de7/tumblr_mx5s2bzbru1qajuaro1_400.gif",
  "https://media.tumblr.com/3a0fbd4a3af87d219f98ae08b9111ebc/tumblr_inline_nky3uqRUdZ1qdyjb2.gif",
  // "https://www.futuregrind.net/press/FutureGrind/images/FutureGrind_01.gif",
  // "https://www.futuregrind.net/press/FutureGrind/images/FutureGrind_02.gif",
  "https://cdn0.vox-cdn.com/uploads/chorus_asset/file/3527562/goofyballhigh.0.gif",
  "https://cdn0.vox-cdn.com/uploads/chorus_asset/file/3527560/canehigh.0.gif",
  "https://i.imgur.com/U9bBdIq.gif",
  "https://media.tumblr.com/e4f99ef7ef7f658eb15fb8f5f97e1bf4/tumblr_nlyh5eTUBX1sa11jco1_500.gif",
  // "https://www.gifbin.com/bin/042012/1333563163_lizard_vs_mouse_cursor.gif",
  "https://d262ilb51hltx0.cloudfront.net/max/800/1*pM_a_s1eGZDw2Dz9-Q9U3A.gif",
  "https://d262ilb51hltx0.cloudfront.net/max/800/1*TDBeD2Oc_BRd_XI4bJ3Arw.gif",
  "https://d262ilb51hltx0.cloudfront.net/max/800/1*-tgctijO2lfJYqYgkZ3cgg.gif",
  "https://giant.gfycat.com/SoupyPlushBumblebee.gif",
  "https://i.imgur.com/9Lc0x63.gif",
  "https://media.tumblr.com/850a238dfa9f2ac5182f477c1d3d7067/tumblr_inline_nlnxpqUnQV1t9bsnt.gif",
  "https://media.giphy.com/media/l41lPS3OHds4idkB2/giphy.gif",
  "https://media0.giphy.com/media/d0SEajOmMna1i/giphy.gif",
  "https://media.giphy.com/media/yoJC2Pa5O4yhG9Gg24/giphy.gif",
  "https://usercontent.irccloud-cdn.com/file/NlkfXBOH/IMG_1706.gif",
  // "https://ak-hdl.buzzfed.com/static/2015-04/16/15/enhanced/webdr02/anigif_enhanced-1066-1429213715-6.gif",
  // "https://cdn1.sciencefiction.com/wp-content/uploads/2014/11/Star-Wars-The-Force-Awakens-Rollie-Pollie-Droid.gif",
  "https://i.imgur.com/lWkLqRP.gif",
  "https://i.imgur.com/vVSY6w6.gif",
  "https://i.imgur.com/1p9EoRQ.gif",
  "https://i.imgur.com/KcSLc2H.gif",
  "https://i.imgur.com/K0WjPGp.gif",
  "https://i.imgur.com/t0dtvFz.gif",
  "https://media.tumblr.com/tumblr_m0dxi6SArw1qbrdf3o1_r1_500.gif",
  "https://media.tumblr.com/6bbb4fd81f57e051221fd22d1e6d8fab/tumblr_nnnfunuRJw1s4fz4bo1_500.gif",
  "https://i.imgur.com/RQ83N2w.gif",
  "https://i.imgur.com/2k5h8qY.gif",
  "https://i.imgur.com/UcGpg7d.gif",
  "https://i.imgur.com/3o6RXe7.gif",
  "https://i.kinja-img.com/gawker-media/image/upload/s--_m0nh6QH--/1272428494394730899.gif",
  "https://media.tumblr.com/db88d6fed2501db48721ebbd73c060a3/tumblr_inline_npfav7mv8O1qzodbd_500.gif",
  "https://i.imgur.com/TV2KHgp.gif",
  "https://lh3.googleusercontent.com/C_NSp7np_qYRSPRpQ-YIaXKeU8ozQoi3UQbbMTHR5E4=w498-h374-no",
  // "https://d13yacurqjgara.cloudfront.net/users/19383/screenshots/969876/switch2.gif",
  "https://media.tumblr.com/3ad3c2cc523d943f009fa8a3be8bda12/tumblr_nklnb632521rt6u7do1_500.gif",
  "https://lh3.googleusercontent.com/EScYkFgTVf9aJifkA_4BU3fUfABuNZKa-3OnX4YUFtk=w972-h730-no",
  "https://lh3.googleusercontent.com/MSGO6BUBSfg4Vry4NSUmpHOfPzUglsX-8KKUjuC7yQM=w498-h374-no",
  "https://media.tumblr.com/b8e64a425c8210c0c524806687aa5fb6/tumblr_nmqb7pIpJH1rxp34uo1_500.gif",
  "https://media.giphy.com/media/2asv1BwbiPRza/giphy.gif",
  "https://media.tumblr.com/fbf76007aa500f710537d21fbbba2076/tumblr_ni8rslXwtc1qh9nffo1_500.gif",
  // "https://stream1.gifsoup.com/view1/20140402/5010921/equalizer-o.gif",
  "https://media.tumblr.com/b33a786188f4cbd9c7052b1132f6fdd9/tumblr_n45c14sSSi1rb06tgo1_250.gif",
  "https://media.tumblr.com/fcebb976d217f932bd9b2ae27c4fb8c4/tumblr_n45c14sSSi1rb06tgo2_250.gif",
  "https://media.tumblr.com/59c1443e3d97782689edeb7d37916b4f/tumblr_n45c14sSSi1rb06tgo3_r1_250.gif",
  "https://media.tumblr.com/17f63db5ca2a7794b4ed4a9637f69892/tumblr_n45c14sSSi1rb06tgo4_r2_250.gif",
  "https://i.imgur.com/zBANAHm.gif",
  // "https://dl.dropboxusercontent.com/u/2301433/Kaelelelele.gif",
  "https://i.imgur.com/SzMpSUX.gif",
  "https://i.imgur.com/fzbW9gf.gif",
  "https://i.imgur.com/jj40tjX.gif",
  "https://i.imgur.com/8mWabkT.gif",
  // "https://d13yacurqjgara.cloudfront.net/users/6191/screenshots/2322843/nationalcatday.gif",
  // "https://s32.postimg.org/djg0enft1/Wiggle.gif",
  "https://lh5.googleusercontent.com/nB1-XV9YvENAPmWq0teZ695J0yWKMtIrtHz8u39uMpBV8BbMzFWJYRfQlxPWyIShMwgE9iXJtcLfAi9ADPSOg6Mu2enIBa71oR5JThr5sIz-WmxK9GNBKAeBpbkNUDGm6q8LNG3h580",
  "https://lh3.googleusercontent.com/D0BBMpP_3j49JKcA5_En6Wht4ndNdf4rYNZNp3aK7kvTT9HUP9_krHmGSPfvE1dmMhrbffd-5IWB0l_H0Bf7g5Dx9CepXyaqA_xqFx-YUkZ6mKwWr7GnQfKUQ90a8iKH25_Vmy9w9V8",
  "https://lh5.googleusercontent.com/0QY-I_6Qm2trNOZ4pOHvBbvK6lSsOaLK2FYsR2TJ1XQoHFgL05AsBEY8mXeP8hJhM2MG4U08lr7yrtHLukGykS6UQM0GufeleDnZVdYj7Zn4BDED5y794Pscq8KflF-BrmqGmI_wk7k",
  "https://lh4.googleusercontent.com/sCXUo8dKg2fjJUCT_Mb7dABGJ0xCumkU-3dvBShCLeWdEM6yk-hFYGjVBsqXUNkv_Xj_Y7C1inxyQVmPkSwwUap659GLGCicNg6I8qwwPYih1-4ZKGYamB17SrBhhlY0mZh8vNLFSng",
  "https://i.imgur.com/V2uFgmS.gif",
  // "https://people-mozilla.org/~smartell/fx/fox-ani-2.gif",
  // "https://dl.dropboxusercontent.com/u/2301433/gifs/jdavidson.gif",
  "https://i.imgur.com/CWKNtbj.gif",
  "https://68.media.tumblr.com/8a62895e18540a85472da0cde1ee21b1/tumblr_n0fjpcEkAf1tooympo1_500.gif",
];

require('dotenv').config();

let deadImages = [];
const port = process.env.PORT || 3000;
const host = process.env.HOST || "0.0.0.0";
const protocol = process.env.PROTOCOL || "http";

const server = Hapi.server({port,host});
const domain = protocol + "://" + host + ":" + port;

function recSwap(data) {
  let src = images[Math.floor(Math.random()*images.length)];
  return {
    ...data,
    image_src: src,
    raw_image_src: src,
  };
}

function componentSwap(data) {
  if (!data.feed || !data.feed.url) {
    return data;
  }
  return {
    ...data,
    feed: {
      ...data.feed,
      url: domain + "/recommendations?url=" + encodeURIComponent(data.feed.url),
    },
  };
}

function layoutSwap(data) {
  return {
    ...data,
    components: data.components.map(componentSwap),
  };
}

function recommendations(data) {
  return {
    ...data,
    recommendations: data.recommendations.map(recSwap),
  };
}

function layout(data) {
  return {
    ...data,
    layout: data.layout.map(layoutSwap),
  };
}

function awaitFetch(url) {
  return new Promise((resolve) => {
    fetch(url)
      .then(res => res.json())
      .then(resolve);
  });
}

const checkImages = async () => {
  for (var i = 0; i < images.length; i++) {
    let image = images[i];
    var result = await imageFetch(image);
    if (result.status !== 200) {
      deadImages.push(result.url);
    }
  }
};

function imageFetch(url) {
  return new Promise((resolve) => {
    fetch(url)
      .then(resolve)
      .catch(e => {
        resolve({url});
      });
  });
}

const init = async () => {

    await server.register(require('inert'));
    server.route([
      {
        method: 'GET',
        path: '/',
        handler: async (request, h) => {
          const url = "https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=3-col-7-row-octr";
          return await awaitFetch(domain + "/layout?url=" + encodeURIComponent(url));
        }
      },
      {
        method: 'GET',
        path: '/layout',
        handler: async (request, h) => {
          const {url} = request.query;
          if (url) {
            return layout(await awaitFetch(url));
          }
          return {"nothing": "1"};
        }
      },
      {
        method: 'GET',
        path: '/recommendations',
        handler: async (request, h) => {
          const {url} = request.query;
          if (url) {
            return recommendations(await awaitFetch(url));
          }
          return {"nothing": "1"};
        }
      }
    ]);

    // await checkImages();
    await server.start();
    console.log("ready");
    console.log(deadImages);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

init();
